project:
  type: website
website:
  title: "Julie Ngo Tran"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: education.qmd
        text: Education
      - text: Projects
        menu:
          - href: "projects/minecraft-auto-close.qmd"
            text: Minecraft Auto Close
          - href: "Assignment 01/bufrjulie8_system_info.qmd"
            text: Assignment 1
          - href: "Module3Lab1/spark_analysis.qmd"
            text: Module 3 Lab 1
          - href: A02-frjulie8.ipynb
            text: Assignment 2
          - href: A03-frjulie8.ipynb
            text: Assignment 3
          - href: A05-frjulie8.ipynb
            text: Assignment 5
          - href: "Module4Lab1/lab06_frjulie8.ipynb"
            text: Module 4 Lab 1
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/julie-ngo-tran-110560220/
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/frjulie8-proj
        aria-label: GitHub
      - icon: envelope
        href: mailto:fromjuliefr@gmail.com
        aria-label: Email
  page-footer:
    left: "© 2026 Julie Ngo Tran"
    right: "Built with [Quarto](https://quarto.org)"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
execute:
  enabled: false
