<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Julie NGO TRAN">
<meta name="dcterms.date" content="2026-06-02">

<title>Module 2 Assignment: Spark SQL and DataFrames</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="A02-frjulie8_files/libs/clipboard/clipboard.min.js"></script>
<script src="A02-frjulie8_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="A02-frjulie8_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="A02-frjulie8_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="A02-frjulie8_files/libs/quarto-html/popper.min.js"></script>
<script src="A02-frjulie8_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="A02-frjulie8_files/libs/quarto-html/anchor.min.js"></script>
<link href="A02-frjulie8_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="A02-frjulie8_files/libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="A02-frjulie8_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="A02-frjulie8_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="A02-frjulie8_files/libs/bootstrap/bootstrap-fd96232d7d733780007c6c25bcda7834.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>
<script>
window.PlotlyConfig = {MathJaxConfig: 'local'};
if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}
</script>
<script type="module">import "https://cdn.plot.ly/plotly-3.6.0.min"</script>



</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul class="collapse">
  <li><a href="#system-information" id="toc-system-information" class="nav-link active" data-scroll-target="#system-information">System Information</a></li>
  <li><a href="#step-1-load-the-dataset-into-spark" id="toc-step-1-load-the-dataset-into-spark" class="nav-link" data-scroll-target="#step-1-load-the-dataset-into-spark"><span class="header-section-number">1</span> Step 1: Load the Dataset into Spark</a></li>
  <li><a href="#step-2-create-relational-tables-in-spark-sql" id="toc-step-2-create-relational-tables-in-spark-sql" class="nav-link" data-scroll-target="#step-2-create-relational-tables-in-spark-sql"><span class="header-section-number">2</span> Step 2: Create Relational Tables in Spark SQL</a></li>
  <li><a href="#step-3-run-sql-queries-in-spark" id="toc-step-3-run-sql-queries-in-spark" class="nav-link" data-scroll-target="#step-3-run-sql-queries-in-spark"><span class="header-section-number">3</span> Step 3: Run SQL Queries in Spark</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Module 2 Assignment: Spark SQL and DataFrames</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Julie NGO TRAN </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Boston University
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 2, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">June 5, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<section id="system-information" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="system-information">System Information</h2>
<div id="6a0e7cca" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> platform</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> psutil</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> subprocess</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Operating System:"</span>, platform.system(), platform.release())</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Python Version:"</span>, platform.python_version())</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Machine:"</span>, platform.machine())</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># EC2 Linux doesn't expose processor via platform.processor()</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Use lscpu instead</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    processor <span class="op">=</span> subprocess.check_output(<span class="st">"lscpu | grep 'Model name'"</span>, shell<span class="op">=</span><span class="va">True</span>).decode().strip()</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    processor <span class="op">=</span> processor.split(<span class="st">":"</span>)[<span class="dv">1</span>].strip()</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span>:</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    processor <span class="op">=</span> <span class="st">"Unable to retrieve"</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Processor:"</span>, processor)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>mem <span class="op">=</span> psutil.virtual_memory()</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Total Memory (MB):"</span>, <span class="bu">round</span>(mem.total <span class="op">/</span> (<span class="dv">1024</span><span class="op">**</span><span class="dv">2</span>), <span class="dv">2</span>))</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Available Memory (MB):"</span>, <span class="bu">round</span>(mem.available <span class="op">/</span> (<span class="dv">1024</span><span class="op">**</span><span class="dv">2</span>), <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Operating System: Linux 7.0.0-1004-aws
Python Version: 3.14.4
Machine: x86_64
Processor: Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Total Memory (MB): 7815.46
Available Memory (MB): 3929.86</code></pre>
</div>
</div>
</section>
<section id="step-1-load-the-dataset-into-spark" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="step-1-load-the-dataset-into-spark"><span class="header-section-number">1</span> Step 1: Load the Dataset into Spark</h2>
<div id="87d4b146" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql <span class="im">import</span> SparkSession</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Start a Spark session</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>spark <span class="op">=</span> SparkSession.builder.config(<span class="st">"spark.driver.host"</span>, <span class="st">"localhost"</span>).appName(<span class="st">"JobPostingsAnalysis"</span>).getOrCreate()</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>spark.catalog.clearCache()</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the CSV file into a Spark DataFrame</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> spark.read.option(<span class="st">"header"</span>, <span class="st">"true"</span>).option(<span class="st">"inferSchema"</span>, <span class="st">"true"</span>).option(</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"multiLine"</span>, <span class="st">"true"</span>).option(<span class="st">"escape"</span>, <span class="st">"</span><span class="ch">\"</span><span class="st">"</span>).csv(<span class="st">"data/lightcast_job_postings.csv"</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Register the DataFrame as a temporary SQL view</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>df.createOrReplaceTempView(<span class="st">"job_postings"</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co"># comment the lines below when rendering the submission</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co"># df.printSchema()</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co"># df.show(5)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 121:&gt;                                                        (0 + 1) / 1]                                                                                </code></pre>
</div>
</div>
</section>
<section id="step-2-create-relational-tables-in-spark-sql" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="step-2-create-relational-tables-in-spark-sql"><span class="header-section-number">2</span> Step 2: Create Relational Tables in Spark SQL</h2>
<section id="industries-table" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="industries-table"><span class="header-section-number">2.1</span> Industries Table</h3>
<div id="5d0c572b" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql.functions <span class="im">import</span> col, monotonically_increasing_id</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>industries_df <span class="op">=</span> df.select(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"NAICS_2022_6"</span>),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"NAICS_2022_6_NAME"</span>),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"SOC_5"</span>),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"SOC_5_NAME"</span>),</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"LOT_SPECIALIZED_OCCUPATION_NAME"</span>),</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"LOT_OCCUPATION_GROUP"</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>).distinct().withColumn(<span class="st">"industry_id"</span>, monotonically_increasing_id())</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>industries_df <span class="op">=</span> industries_df.select(</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"industry_id"</span>,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"NAICS_2022_6"</span>,</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"NAICS_2022_6_NAME"</span>,</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SOC_5"</span>,</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SOC_5_NAME"</span>,</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"LOT_SPECIALIZED_OCCUPATION_NAME"</span>,</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"LOT_OCCUPATION_GROUP"</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Save as CSV</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>industries_df.write.mode(<span class="st">"overwrite"</span>).csv(<span class="st">"output/industries.csv"</span>, header<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Register as SQL view</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>industries_df.createOrReplaceTempView(<span class="st">"industries"</span>)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>industries_df.show(<span class="dv">5</span>, truncate<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Pandas conversion for display</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>industries_df.toPandas()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 122:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 125:&gt;                                                        (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+-----------+------------+-------------------------------------------------------+-------+---------------+--------------------------------+--------------------+
|industry_id|NAICS_2022_6|NAICS_2022_6_NAME                                      |SOC_5  |SOC_5_NAME     |LOT_SPECIALIZED_OCCUPATION_NAME |LOT_OCCUPATION_GROUP|
+-----------+------------+-------------------------------------------------------+-------+---------------+--------------------------------+--------------------+
|0          |424490      |Other Grocery and Related Products Merchant Wholesalers|15-2051|Data Scientists|SAP Analyst / Admin             |2310                |
|1          |562111      |Solid Waste Collection                                 |15-2051|Data Scientists|Oracle Consultant / Analyst     |2310                |
|2          |457110      |Gasoline Stations with Convenience Stores              |15-2051|Data Scientists|Oracle Consultant / Analyst     |2310                |
|3          |334111      |Electronic Computer Manufacturing                      |15-2051|Data Scientists|Oracle Consultant / Analyst     |2310                |
|4          |621320      |Offices of Optometrists                                |15-2051|Data Scientists|General ERP Analyst / Consultant|2310                |
+-----------+------------+-------------------------------------------------------+-------+---------------+--------------------------------+--------------------+
only showing top 5 rows</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 128:&gt;                                                        (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="14">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">industry_id</th>
<th data-quarto-table-cell-role="th">NAICS_2022_6</th>
<th data-quarto-table-cell-role="th">NAICS_2022_6_NAME</th>
<th data-quarto-table-cell-role="th">SOC_5</th>
<th data-quarto-table-cell-role="th">SOC_5_NAME</th>
<th data-quarto-table-cell-role="th">LOT_SPECIALIZED_OCCUPATION_NAME</th>
<th data-quarto-table-cell-role="th">LOT_OCCUPATION_GROUP</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0</td>
<td>424490.0</td>
<td>Other Grocery and Related Products Merchant Wh...</td>
<td>15-2051</td>
<td>Data Scientists</td>
<td>SAP Analyst / Admin</td>
<td>2310.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>1</td>
<td>562111.0</td>
<td>Solid Waste Collection</td>
<td>15-2051</td>
<td>Data Scientists</td>
<td>Oracle Consultant / Analyst</td>
<td>2310.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>2</td>
<td>457110.0</td>
<td>Gasoline Stations with Convenience Stores</td>
<td>15-2051</td>
<td>Data Scientists</td>
<td>Oracle Consultant / Analyst</td>
<td>2310.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>3</td>
<td>334111.0</td>
<td>Electronic Computer Manufacturing</td>
<td>15-2051</td>
<td>Data Scientists</td>
<td>Oracle Consultant / Analyst</td>
<td>2310.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>4</td>
<td>621320.0</td>
<td>Offices of Optometrists</td>
<td>15-2051</td>
<td>Data Scientists</td>
<td>General ERP Analyst / Consultant</td>
<td>2310.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">...</th>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">3341</th>
<td>3341</td>
<td>211120.0</td>
<td>Crude Petroleum Extraction</td>
<td>15-2051</td>
<td>Data Scientists</td>
<td>Business Analyst (General)</td>
<td>1111.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3342</th>
<td>3342</td>
<td>314110.0</td>
<td>Carpet and Rug Mills</td>
<td>15-2051</td>
<td>Data Scientists</td>
<td>Enterprise Architect</td>
<td>2315.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">3343</th>
<td>3343</td>
<td>333992.0</td>
<td>Welding and Soldering Equipment Manufacturing</td>
<td>15-2051</td>
<td>Data Scientists</td>
<td>General ERP Analyst / Consultant</td>
<td>2310.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3344</th>
<td>3344</td>
<td>423490.0</td>
<td>Other Professional Equipment and Supplies Merc...</td>
<td>15-2051</td>
<td>Data Scientists</td>
<td>SAP Analyst / Admin</td>
<td>2310.0</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">3345</th>
<td>3345</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

<p>3346 rows × 7 columns</p>
</div>
</div>
</div>
</section>
<section id="companies-table" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="companies-table"><span class="header-section-number">2.2</span> Companies Table</h3>
<div id="f6a790c2" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>companies_df <span class="op">=</span> df.select(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"COMPANY"</span>),</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"COMPANY_NAME"</span>),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"COMPANY_RAW"</span>),</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"COMPANY_IS_STAFFING"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>).distinct().withColumn(<span class="st">"company_id"</span>, monotonically_increasing_id())</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>companies_df <span class="op">=</span> companies_df.select(</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"company_id"</span>,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"COMPANY"</span>,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"COMPANY_NAME"</span>,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"COMPANY_RAW"</span>,</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"COMPANY_IS_STAFFING"</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Save as CSV</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>companies_df.write.mode(<span class="st">"overwrite"</span>).csv(<span class="st">"output/companies.csv"</span>, header<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Register as SQL view</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>companies_df.createOrReplaceTempView(<span class="st">"companies"</span>)</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>companies_df.show(<span class="dv">5</span>, truncate<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Pandas conversion for display</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>companies_df.toPandas()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 131:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 134:&gt;                                                        (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+----------+--------+-------------------------------------------------+-------------------------------------------------+-------------------+
|company_id|COMPANY |COMPANY_NAME                                     |COMPANY_RAW                                      |COMPANY_IS_STAFFING|
+----------+--------+-------------------------------------------------+-------------------------------------------------+-------------------+
|0         |35247729|Crowe                                            |Crowe                                            |false              |
|1         |39461288|The Devereux Foundation                          |The Devereux Foundation                          |false              |
|2         |40008275|Elder Research                                   |Elder Research                                   |false              |
|3         |37060425|NTT DATA                                         |NTT DATA Inc                                     |false              |
|4         |40882284|Frederick National Laboratory For Cancer Research|Frederick National Laboratory for Cancer Research|false              |
+----------+--------+-------------------------------------------------+-------------------------------------------------+-------------------+
only showing top 5 rows</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 137:&gt;                                                        (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="15">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">company_id</th>
<th data-quarto-table-cell-role="th">COMPANY</th>
<th data-quarto-table-cell-role="th">COMPANY_NAME</th>
<th data-quarto-table-cell-role="th">COMPANY_RAW</th>
<th data-quarto-table-cell-role="th">COMPANY_IS_STAFFING</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0</td>
<td>35247729.0</td>
<td>Crowe</td>
<td>Crowe</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>1</td>
<td>39461288.0</td>
<td>The Devereux Foundation</td>
<td>The Devereux Foundation</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>2</td>
<td>40008275.0</td>
<td>Elder Research</td>
<td>Elder Research</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>3</td>
<td>37060425.0</td>
<td>NTT DATA</td>
<td>NTT DATA Inc</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>4</td>
<td>40882284.0</td>
<td>Frederick National Laboratory For Cancer Research</td>
<td>Frederick National Laboratory for Cancer Research</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">...</th>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">17269</th>
<td>17269</td>
<td>39377411.0</td>
<td>E Business Corp</td>
<td>E-Business International Inc</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">17270</th>
<td>17270</td>
<td>37725500.0</td>
<td>Poshmark</td>
<td>Poshmark</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">17271</th>
<td>17271</td>
<td>38311242.0</td>
<td>Advanced Medical</td>
<td>Advanced Medical Corp.</td>
<td>False</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">17272</th>
<td>17272</td>
<td>39254051.0</td>
<td>Seaworld Entertainment</td>
<td>SeaWorld Entertainment, Inc.</td>
<td>False</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">17273</th>
<td>17273</td>
<td>39043822.0</td>
<td>G3 Enterprises</td>
<td>G3 Enterprises</td>
<td>False</td>
</tr>
</tbody>
</table>

<p>17274 rows × 5 columns</p>
</div>
</div>
</div>
</section>
<section id="locations-table" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="locations-table"><span class="header-section-number">2.3</span> Locations Table</h3>
<div id="fb66c3f4" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>locations_df <span class="op">=</span> df.select(</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"LOCATION"</span>),</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"CITY_NAME"</span>),</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"STATE_NAME"</span>),</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"COUNTY_NAME"</span>),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"MSA"</span>),</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    col(<span class="st">"MSA_NAME"</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>).distinct().withColumn(<span class="st">"location_id"</span>, monotonically_increasing_id())</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>locations_df <span class="op">=</span> locations_df.select(</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"location_id"</span>,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"LOCATION"</span>,</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"CITY_NAME"</span>,</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"STATE_NAME"</span>,</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"COUNTY_NAME"</span>,</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"MSA"</span>,</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"MSA_NAME"</span></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Save as CSV</span></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>locations_df.write.mode(<span class="st">"overwrite"</span>).csv(<span class="st">"output/locations.csv"</span>, header<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Register as SQL view</span></span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>locations_df.createOrReplaceTempView(<span class="st">"locations"</span>)</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>locations_df.show(<span class="dv">5</span>, truncate<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Pandas conversion for display</span></span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>locations_df.toPandas()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 140:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 143:&gt;                                                        (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+-----------+------------------------------------------------+------------------+----------+-----------+-----+-------------------------------------+
|location_id|LOCATION                                        |CITY_NAME         |STATE_NAME|COUNTY_NAME|MSA  |MSA_NAME                             |
+-----------+------------------------------------------------+------------------+----------+-----------+-----+-------------------------------------+
|0          |{\n  "lat": 24.5550593,\n  "lon": -81.7799871\n}|Key West, FL      |Florida   |Monroe, FL |28580|Key West, FL                         |
|1          |{\n  "lat": 41.6266555,\n  "lon": -93.7121656\n}|Urbandale, IA     |Iowa      |Polk, IA   |19780|Des Moines-West Des Moines, IA       |
|2          |{\n  "lat": 37.2089572,\n  "lon": -93.2922989\n}|Springfield, MO   |Missouri  |Greene, MO |44180|Springfield, MO                      |
|3          |{\n  "lat": 40.7453199,\n  "lon": -74.0535126\n}|[Unknown City], NJ|New Jersey|Hudson, NJ |35620|New York-Newark-Jersey City, NY-NJ-PA|
|4          |{\n  "lat": 40.7985699,\n  "lon": -74.2390828\n}|West Orange, NJ   |New Jersey|Essex, NJ  |35620|New York-Newark-Jersey City, NY-NJ-PA|
+-----------+------------------------------------------------+------------------+----------+-----------+-----+-------------------------------------+
only showing top 5 rows</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 146:&gt;                                                        (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="16">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">location_id</th>
<th data-quarto-table-cell-role="th">LOCATION</th>
<th data-quarto-table-cell-role="th">CITY_NAME</th>
<th data-quarto-table-cell-role="th">STATE_NAME</th>
<th data-quarto-table-cell-role="th">COUNTY_NAME</th>
<th data-quarto-table-cell-role="th">MSA</th>
<th data-quarto-table-cell-role="th">MSA_NAME</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0</td>
<td>{\n&nbsp;&nbsp;"lat": 24.5550593,\n&nbsp;&nbsp;"lon": -81.7799871\n}</td>
<td>Key West, FL</td>
<td>Florida</td>
<td>Monroe, FL</td>
<td>28580.0</td>
<td>Key West, FL</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>1</td>
<td>{\n&nbsp;&nbsp;"lat": 41.6266555,\n&nbsp;&nbsp;"lon": -93.7121656\n}</td>
<td>Urbandale, IA</td>
<td>Iowa</td>
<td>Polk, IA</td>
<td>19780.0</td>
<td>Des Moines-West Des Moines, IA</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>2</td>
<td>{\n&nbsp;&nbsp;"lat": 37.2089572,\n&nbsp;&nbsp;"lon": -93.2922989\n}</td>
<td>Springfield, MO</td>
<td>Missouri</td>
<td>Greene, MO</td>
<td>44180.0</td>
<td>Springfield, MO</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>3</td>
<td>{\n&nbsp;&nbsp;"lat": 40.7453199,\n&nbsp;&nbsp;"lon": -74.0535126\n}</td>
<td>[Unknown City], NJ</td>
<td>New Jersey</td>
<td>Hudson, NJ</td>
<td>35620.0</td>
<td>New York-Newark-Jersey City, NY-NJ-PA</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>4</td>
<td>{\n&nbsp;&nbsp;"lat": 40.7985699,\n&nbsp;&nbsp;"lon": -74.2390828\n}</td>
<td>West Orange, NJ</td>
<td>New Jersey</td>
<td>Essex, NJ</td>
<td>35620.0</td>
<td>New York-Newark-Jersey City, NY-NJ-PA</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">...</th>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">5169</th>
<td>5169</td>
<td>{\n&nbsp;&nbsp;"lat": 37.7761531,\n&nbsp;&nbsp;"lon": -91.7309873\n}</td>
<td>Lecoma, MO</td>
<td>Missouri</td>
<td>Dent, MO</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5170</th>
<td>5170</td>
<td>{\n&nbsp;&nbsp;"lat": 32.3182314,\n&nbsp;&nbsp;"lon": -86.902298\n}</td>
<td>[Unknown City], AL</td>
<td>Alabama</td>
<td>[Unknown county], AL</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">5171</th>
<td>5171</td>
<td>{\n&nbsp;&nbsp;"lat": 43.0759678,\n&nbsp;&nbsp;"lon": -107.2902839\n}</td>
<td>[Unknown City], WY</td>
<td>Wyoming</td>
<td>[Unknown county], WY</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5172</th>
<td>5172</td>
<td>{\n&nbsp;&nbsp;"lat": 55.6877778,\n&nbsp;&nbsp;"lon": -132.5222222\n}</td>
<td>Thorne Bay, AK</td>
<td>Alaska</td>
<td>Prince of Wales-Hyder Census Area, AK</td>
<td>NaN</td>
<td>NaN</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">5173</th>
<td>5173</td>
<td>{\n&nbsp;&nbsp;"lat": 0,\n&nbsp;&nbsp;"lon": 0\n}</td>
<td>[Unknown City], IN</td>
<td>Indiana</td>
<td>[Unknown county], IN</td>
<td>NaN</td>
<td>NaN</td>
</tr>
</tbody>
</table>

<p>5174 rows × 7 columns</p>
</div>
</div>
</div>
</section>
<section id="job-postings-table" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="job-postings-table"><span class="header-section-number">2.4</span> Job Postings Table</h3>
<div id="95935056" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>df_with_id <span class="op">=</span> df.withColumnRenamed(<span class="st">"COMPANY"</span>, <span class="st">"jp_COMPANY"</span>) <span class="op">\</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>               .withColumnRenamed(<span class="st">"COMPANY_NAME"</span>, <span class="st">"jp_COMPANY_NAME"</span>) <span class="op">\</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>               .withColumnRenamed(<span class="st">"NAICS_2022_6"</span>, <span class="st">"jp_NAICS_2022_6"</span>) <span class="op">\</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>               .withColumnRenamed(<span class="st">"SOC_5"</span>, <span class="st">"jp_SOC_5"</span>) <span class="op">\</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>               .withColumnRenamed(<span class="st">"CITY_NAME"</span>, <span class="st">"jp_CITY_NAME"</span>) <span class="op">\</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>               .withColumnRenamed(<span class="st">"STATE_NAME"</span>, <span class="st">"jp_STATE_NAME"</span>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>job_postings_df <span class="op">=</span> df_with_id <span class="op">\</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>.join(companies_df, df_with_id[<span class="st">"jp_COMPANY"</span>] <span class="op">==</span> companies_df[<span class="st">"COMPANY"</span>], <span class="st">"left"</span>) <span class="op">\</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>.join(industries_df,</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>    (df_with_id[<span class="st">"jp_NAICS_2022_6"</span>] <span class="op">==</span> industries_df[<span class="st">"NAICS_2022_6"</span>]) <span class="op">&amp;</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>    (df_with_id[<span class="st">"jp_SOC_5"</span>] <span class="op">==</span> industries_df[<span class="st">"SOC_5"</span>]),</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"left"</span>) <span class="op">\</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>.join(locations_df,</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>    (df_with_id[<span class="st">"jp_CITY_NAME"</span>] <span class="op">==</span> locations_df[<span class="st">"CITY_NAME"</span>]) <span class="op">&amp;</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>    (df_with_id[<span class="st">"jp_STATE_NAME"</span>] <span class="op">==</span> locations_df[<span class="st">"STATE_NAME"</span>]),</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"left"</span>) <span class="op">\</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>.select(</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>    df_with_id[<span class="st">"ID"</span>],</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>    df_with_id[<span class="st">"TITLE_CLEAN"</span>],</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>    companies_df[<span class="st">"company_id"</span>],</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>    industries_df[<span class="st">"industry_id"</span>],</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>    df_with_id[<span class="st">"EMPLOYMENT_TYPE_NAME"</span>],</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>    df_with_id[<span class="st">"REMOTE_TYPE_NAME"</span>],</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>    df_with_id[<span class="st">"BODY"</span>],</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>    df_with_id[<span class="st">"MIN_YEARS_EXPERIENCE"</span>],</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>    df_with_id[<span class="st">"MAX_YEARS_EXPERIENCE"</span>],</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>    df_with_id[<span class="st">"SALARY"</span>],</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>    df_with_id[<span class="st">"SALARY_FROM"</span>],</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>    df_with_id[<span class="st">"SALARY_TO"</span>],</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>    locations_df[<span class="st">"location_id"</span>],</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>    df_with_id[<span class="st">"POSTED"</span>],</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>    df_with_id[<span class="st">"EXPIRED"</span>],</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>    df_with_id[<span class="st">"DURATION"</span>]</span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Register as SQL view</span></span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>job_postings_df.createOrReplaceTempView(<span class="st">"job_postings"</span>)</span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>job_postings_df.show(<span class="dv">5</span>, truncate<span class="op">=</span><span class="va">False</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 149:&gt;  (0 + 1) / 1][Stage 150:&gt;  (0 + 1) / 1][Stage 151:&gt;  (0 + 0) / 1][Stage 149:&gt;                (0 + 1) / 1][Stage 151:&gt;                (0 + 1) / 1][Stage 151:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 151:&gt;                                                        (0 + 1) / 1]</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+----------------------------------------+-------------------------+----------+-----------+----------------------+----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+--------------------+------+-----------+---------+-----------+--------+--------+--------+
|ID                                      |TITLE_CLEAN              |company_id|industry_id|EMPLOYMENT_TYPE_NAME  |REMOTE_TYPE_NAME|BODY                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |MIN_YEARS_EXPERIENCE|MAX_YEARS_EXPERIENCE|SALARY|SALARY_FROM|SALARY_TO|location_id|POSTED  |EXPIRED |DURATION|
+----------------------------------------+-------------------------+----------+-----------+----------------------+----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+--------------------+------+-----------+---------+-----------+--------+--------+--------+
|1f57d95acf4dc67ed2819eb12f049f6a5c11782c|enterprise analyst ii iii|14586     |1753       |Full-time (&gt; 32 hours)|[None]          |31-May-2024\n\nEnterprise Analyst (II-III)\n\nMerchandising\n\nEl Dorado\n\nArkansas\n\nJob Posting\n\nGENERAL DESCRIPTION OF POSITION\nPerforms business analysis using various techniques, e.g. statistical analysis, explanatory and predictive modeling, data mining. Identifies trends and patterns in data and can explain business drivers or the why behind the data. Skills typically attained in a four-year degree plus the understanding and application of analytical tools and techniques that come with 2-5 years of experience including advanced MS office skills, advanced SQL, PowerBI, and exporting/building data models.\n\nESSENTIAL DUTIES AND RESPONSIBILITIES\n1. Gathers insight and performs routine and ad hoc reporting using various techniques (statistical analysis, data mining).\n2. Frames unstructured problems\n3. Performs data extraction/gathering, reconciling ambiguous data, and executes the hypothesis-driven approach.\n4. Develops fact-based and actionable recommendations/presentations.\n5. Analyze data for trends and patterns, and interpret data with a clear objective in mind\n6. Proficiently design and develop algorithms and models to use against large datasets to create business insights\n7. Make appropriate selection, utilization and interpretation of advanced analytical methodologies\n8. Effectively communicate insights and recommendations to both technical and non-technical leaders and business customers/partners including preparing reports, updates and/or presentations related to progress made on a project or solution\n9. Work with project teams and business partners to determine project goals and deliver productionized models and tools\n10. Effectively develop trust and collaboration with internal customers and cross-functional teams\n\n\nQUALIFICATIONS\nTo perform this job successfully, an individual must be able to perform each essential duty mentioned satisfactorily. The requirements listed below are representative of the knowledge, skill, and/or ability required.\n\nEDUCATION AND EXPERIENCE\nBroad knowledge of such fields as economics, statistics, business administration, finance, math, science etc. Equivalent to a four-year college degree, plus 2-5 years related experience and/or training, or equivalent combination of education and experience.\n\nAuto req ID\n\n181767BR\n\nStore Number/Dept Number\n\n299900055000 - Strat Plan Perform Mgmt\n\nStore Address\n\n200 E Peach St\n\nStore Zip\n\n71730|2                   |2                   |NULL  |NULL       |NULL     |3878       |6/2/2024|6/8/2024|6       |
|1f57d95acf4dc67ed2819eb12f049f6a5c11782c|enterprise analyst ii iii|14586     |1616       |Full-time (&gt; 32 hours)|[None]          |31-May-2024\n\nEnterprise Analyst (II-III)\n\nMerchandising\n\nEl Dorado\n\nArkansas\n\nJob Posting\n\nGENERAL DESCRIPTION OF POSITION\nPerforms business analysis using various techniques, e.g. statistical analysis, explanatory and predictive modeling, data mining. Identifies trends and patterns in data and can explain business drivers or the why behind the data. Skills typically attained in a four-year degree plus the understanding and application of analytical tools and techniques that come with 2-5 years of experience including advanced MS office skills, advanced SQL, PowerBI, and exporting/building data models.\n\nESSENTIAL DUTIES AND RESPONSIBILITIES\n1. Gathers insight and performs routine and ad hoc reporting using various techniques (statistical analysis, data mining).\n2. Frames unstructured problems\n3. Performs data extraction/gathering, reconciling ambiguous data, and executes the hypothesis-driven approach.\n4. Develops fact-based and actionable recommendations/presentations.\n5. Analyze data for trends and patterns, and interpret data with a clear objective in mind\n6. Proficiently design and develop algorithms and models to use against large datasets to create business insights\n7. Make appropriate selection, utilization and interpretation of advanced analytical methodologies\n8. Effectively communicate insights and recommendations to both technical and non-technical leaders and business customers/partners including preparing reports, updates and/or presentations related to progress made on a project or solution\n9. Work with project teams and business partners to determine project goals and deliver productionized models and tools\n10. Effectively develop trust and collaboration with internal customers and cross-functional teams\n\n\nQUALIFICATIONS\nTo perform this job successfully, an individual must be able to perform each essential duty mentioned satisfactorily. The requirements listed below are representative of the knowledge, skill, and/or ability required.\n\nEDUCATION AND EXPERIENCE\nBroad knowledge of such fields as economics, statistics, business administration, finance, math, science etc. Equivalent to a four-year college degree, plus 2-5 years related experience and/or training, or equivalent combination of education and experience.\n\nAuto req ID\n\n181767BR\n\nStore Number/Dept Number\n\n299900055000 - Strat Plan Perform Mgmt\n\nStore Address\n\n200 E Peach St\n\nStore Zip\n\n71730|2                   |2                   |NULL  |NULL       |NULL     |3878       |6/2/2024|6/8/2024|6       |
|1f57d95acf4dc67ed2819eb12f049f6a5c11782c|enterprise analyst ii iii|14586     |1024       |Full-time (&gt; 32 hours)|[None]          |31-May-2024\n\nEnterprise Analyst (II-III)\n\nMerchandising\n\nEl Dorado\n\nArkansas\n\nJob Posting\n\nGENERAL DESCRIPTION OF POSITION\nPerforms business analysis using various techniques, e.g. statistical analysis, explanatory and predictive modeling, data mining. Identifies trends and patterns in data and can explain business drivers or the why behind the data. Skills typically attained in a four-year degree plus the understanding and application of analytical tools and techniques that come with 2-5 years of experience including advanced MS office skills, advanced SQL, PowerBI, and exporting/building data models.\n\nESSENTIAL DUTIES AND RESPONSIBILITIES\n1. Gathers insight and performs routine and ad hoc reporting using various techniques (statistical analysis, data mining).\n2. Frames unstructured problems\n3. Performs data extraction/gathering, reconciling ambiguous data, and executes the hypothesis-driven approach.\n4. Develops fact-based and actionable recommendations/presentations.\n5. Analyze data for trends and patterns, and interpret data with a clear objective in mind\n6. Proficiently design and develop algorithms and models to use against large datasets to create business insights\n7. Make appropriate selection, utilization and interpretation of advanced analytical methodologies\n8. Effectively communicate insights and recommendations to both technical and non-technical leaders and business customers/partners including preparing reports, updates and/or presentations related to progress made on a project or solution\n9. Work with project teams and business partners to determine project goals and deliver productionized models and tools\n10. Effectively develop trust and collaboration with internal customers and cross-functional teams\n\n\nQUALIFICATIONS\nTo perform this job successfully, an individual must be able to perform each essential duty mentioned satisfactorily. The requirements listed below are representative of the knowledge, skill, and/or ability required.\n\nEDUCATION AND EXPERIENCE\nBroad knowledge of such fields as economics, statistics, business administration, finance, math, science etc. Equivalent to a four-year college degree, plus 2-5 years related experience and/or training, or equivalent combination of education and experience.\n\nAuto req ID\n\n181767BR\n\nStore Number/Dept Number\n\n299900055000 - Strat Plan Perform Mgmt\n\nStore Address\n\n200 E Peach St\n\nStore Zip\n\n71730|2                   |2                   |NULL  |NULL       |NULL     |3878       |6/2/2024|6/8/2024|6       |
|1f57d95acf4dc67ed2819eb12f049f6a5c11782c|enterprise analyst ii iii|14586     |942        |Full-time (&gt; 32 hours)|[None]          |31-May-2024\n\nEnterprise Analyst (II-III)\n\nMerchandising\n\nEl Dorado\n\nArkansas\n\nJob Posting\n\nGENERAL DESCRIPTION OF POSITION\nPerforms business analysis using various techniques, e.g. statistical analysis, explanatory and predictive modeling, data mining. Identifies trends and patterns in data and can explain business drivers or the why behind the data. Skills typically attained in a four-year degree plus the understanding and application of analytical tools and techniques that come with 2-5 years of experience including advanced MS office skills, advanced SQL, PowerBI, and exporting/building data models.\n\nESSENTIAL DUTIES AND RESPONSIBILITIES\n1. Gathers insight and performs routine and ad hoc reporting using various techniques (statistical analysis, data mining).\n2. Frames unstructured problems\n3. Performs data extraction/gathering, reconciling ambiguous data, and executes the hypothesis-driven approach.\n4. Develops fact-based and actionable recommendations/presentations.\n5. Analyze data for trends and patterns, and interpret data with a clear objective in mind\n6. Proficiently design and develop algorithms and models to use against large datasets to create business insights\n7. Make appropriate selection, utilization and interpretation of advanced analytical methodologies\n8. Effectively communicate insights and recommendations to both technical and non-technical leaders and business customers/partners including preparing reports, updates and/or presentations related to progress made on a project or solution\n9. Work with project teams and business partners to determine project goals and deliver productionized models and tools\n10. Effectively develop trust and collaboration with internal customers and cross-functional teams\n\n\nQUALIFICATIONS\nTo perform this job successfully, an individual must be able to perform each essential duty mentioned satisfactorily. The requirements listed below are representative of the knowledge, skill, and/or ability required.\n\nEDUCATION AND EXPERIENCE\nBroad knowledge of such fields as economics, statistics, business administration, finance, math, science etc. Equivalent to a four-year college degree, plus 2-5 years related experience and/or training, or equivalent combination of education and experience.\n\nAuto req ID\n\n181767BR\n\nStore Number/Dept Number\n\n299900055000 - Strat Plan Perform Mgmt\n\nStore Address\n\n200 E Peach St\n\nStore Zip\n\n71730|2                   |2                   |NULL  |NULL       |NULL     |3878       |6/2/2024|6/8/2024|6       |
|1f57d95acf4dc67ed2819eb12f049f6a5c11782c|enterprise analyst ii iii|14586     |400        |Full-time (&gt; 32 hours)|[None]          |31-May-2024\n\nEnterprise Analyst (II-III)\n\nMerchandising\n\nEl Dorado\n\nArkansas\n\nJob Posting\n\nGENERAL DESCRIPTION OF POSITION\nPerforms business analysis using various techniques, e.g. statistical analysis, explanatory and predictive modeling, data mining. Identifies trends and patterns in data and can explain business drivers or the why behind the data. Skills typically attained in a four-year degree plus the understanding and application of analytical tools and techniques that come with 2-5 years of experience including advanced MS office skills, advanced SQL, PowerBI, and exporting/building data models.\n\nESSENTIAL DUTIES AND RESPONSIBILITIES\n1. Gathers insight and performs routine and ad hoc reporting using various techniques (statistical analysis, data mining).\n2. Frames unstructured problems\n3. Performs data extraction/gathering, reconciling ambiguous data, and executes the hypothesis-driven approach.\n4. Develops fact-based and actionable recommendations/presentations.\n5. Analyze data for trends and patterns, and interpret data with a clear objective in mind\n6. Proficiently design and develop algorithms and models to use against large datasets to create business insights\n7. Make appropriate selection, utilization and interpretation of advanced analytical methodologies\n8. Effectively communicate insights and recommendations to both technical and non-technical leaders and business customers/partners including preparing reports, updates and/or presentations related to progress made on a project or solution\n9. Work with project teams and business partners to determine project goals and deliver productionized models and tools\n10. Effectively develop trust and collaboration with internal customers and cross-functional teams\n\n\nQUALIFICATIONS\nTo perform this job successfully, an individual must be able to perform each essential duty mentioned satisfactorily. The requirements listed below are representative of the knowledge, skill, and/or ability required.\n\nEDUCATION AND EXPERIENCE\nBroad knowledge of such fields as economics, statistics, business administration, finance, math, science etc. Equivalent to a four-year college degree, plus 2-5 years related experience and/or training, or equivalent combination of education and experience.\n\nAuto req ID\n\n181767BR\n\nStore Number/Dept Number\n\n299900055000 - Strat Plan Perform Mgmt\n\nStore Address\n\n200 E Peach St\n\nStore Zip\n\n71730|2                   |2                   |NULL  |NULL       |NULL     |3878       |6/2/2024|6/8/2024|6       |
+----------------------------------------+-------------------------+----------+-----------+----------------------+----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+--------------------+------+-----------+---------+-----------+--------+--------+--------+
only showing top 5 rows</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>                                                                                </code></pre>
</div>
</div>
</section>
</section>
<section id="step-3-run-sql-queries-in-spark" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="step-3-run-sql-queries-in-spark"><span class="header-section-number">3</span> Step 3: Run SQL Queries in Spark</h2>
<section id="example-query-top-5-most-posted-job-titles" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="example-query-top-5-most-posted-job-titles"><span class="header-section-number">3.1</span> Example Query: Top 5 Most Posted Job Titles</h3>
<div id="608b3891" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>top5 <span class="op">=</span> spark.sql(<span class="st">"""</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="st">    SELECT TITLE_CLEAN, COUNT(*) AS job_count</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="st">    FROM job_postings</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="st">    GROUP BY TITLE_CLEAN</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="st">    ORDER BY job_count DESC</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="st">    LIMIT 5</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span>)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>top5.show(truncate<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>top5.toPandas()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 161:&gt;  (0 + 1) / 1][Stage 162:&gt;  (0 + 1) / 1][Stage 163:&gt;  (0 + 0) / 1][Stage 162:&gt;                (0 + 1) / 1][Stage 163:&gt;                (0 + 1) / 1][Stage 163:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 163:&gt;                                                        (0 + 1) / 1][Stage 163:&gt;                (0 + 1) / 1][Stage 168:&gt;                (0 + 1) / 1][Stage 168:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 168:&gt;                                                        (0 + 1) / 1][Stage 168:&gt;                                                        (0 + 1) / 1][Stage 172:&gt;                                                        (0 + 2) / 2][Stage 172:&gt;                                                        (0 + 2) / 2][Stage 172:&gt;                                                        (0 + 2) / 2][Stage 172:============================&gt;                            (1 + 1) / 2]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+----------------------------------------------------+---------+
|TITLE_CLEAN                                         |job_count|
+----------------------------------------------------+---------+
|data analyst                                        |63889634 |
|enterprise architect                                |11938984 |
|senior data analyst                                 |6915422  |
|entry level data analyst application via ripplematch|5664736  |
|data modeler                                        |5153279  |
+----------------------------------------------------+---------+
</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 176:&gt;                (0 + 1) / 1][Stage 177:&gt;                (0 + 1) / 1][Stage 176:&gt;  (0 + 1) / 1][Stage 177:&gt;  (0 + 1) / 1][Stage 178:&gt;  (0 + 0) / 1][Stage 177:&gt;                (0 + 1) / 1][Stage 178:&gt;                (0 + 1) / 1]                                                                                [Stage 178:&gt;                                                        (0 + 1) / 1][Stage 178:&gt;                (0 + 1) / 1][Stage 183:&gt;                (0 + 1) / 1][Stage 183:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 183:&gt;                                                        (0 + 1) / 1][Stage 183:&gt;                                                        (0 + 1) / 1][Stage 187:&gt;                                                        (0 + 2) / 2][Stage 187:&gt;                                                        (0 + 2) / 2][Stage 187:&gt;                                                        (0 + 2) / 2][Stage 187:============================&gt;                            (1 + 1) / 2]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="18">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">TITLE_CLEAN</th>
<th data-quarto-table-cell-role="th">job_count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>data analyst</td>
<td>63889634</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>enterprise architect</td>
<td>11938984</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>senior data analyst</td>
<td>6915422</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>entry level data analyst application via rippl...</td>
<td>5664736</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>data modeler</td>
<td>5153279</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="query-1-average-salary-by-tech-industry" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="query-1-average-salary-by-tech-industry"><span class="header-section-number">3.2</span> Query 1: Average Salary by Tech Industry</h3>
<blockquote class="blockquote">
<p><strong>Note on Query 1 Approach:</strong> The Lightcast dataset stores salary data as pre-aggregated industry-level values, meaning all occupations within the same NAICS code share identical salary figures. Therefore, instead of grouping by specialized occupation as instructed, we group by NAICS industry code across five major tech sectors (518210, 541511, 541512, 541519, 334111) to produce meaningful salary variation. This reflects a data limitation of Lightcast’s pre-summarized compensation model rather than an analytical choice.</p>
</blockquote>
<div id="8aab7012" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>query1 <span class="op">=</span> spark.sql(<span class="st">"""</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="st">    SELECT </span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="st">        i.NAICS_2022_6_NAME AS industry_name,</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="st">        ROUND(AVG((j.SALARY_FROM + j.SALARY_TO) / 2), 2) AS avg_salary,</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="st">        COUNT(DISTINCT j.ID) AS job_count</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="st">    FROM job_postings j</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="st">    JOIN industries i ON j.industry_id = i.industry_id</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="st">    WHERE i.NAICS_2022_6 IN (518210, 541511, 541512, 541519, 334111)</span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="st">    AND j.SALARY_FROM IS NOT NULL</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="st">    AND j.SALARY_TO IS NOT NULL</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a><span class="st">    AND j.SALARY_FROM &gt; 0</span></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="st">    AND j.SALARY_TO &gt; 0</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a><span class="st">    GROUP BY i.NAICS_2022_6_NAME</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a><span class="st">    ORDER BY avg_salary DESC</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span>)</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a>query1.show(truncate<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>query1_pd <span class="op">=</span> query1.toPandas()</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>query1_pd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 191:&gt;  (0 + 1) / 1][Stage 192:&gt;  (0 + 1) / 1][Stage 193:&gt;  (0 + 0) / 1][Stage 192:&gt;                (0 + 1) / 1][Stage 193:&gt;                (0 + 1) / 1][Stage 193:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 193:&gt;                (0 + 1) / 1][Stage 198:&gt;                (0 + 1) / 1][Stage 198:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 198:&gt;                                                        (0 + 1) / 1][Stage 203:&gt;                                                        (0 + 2) / 2][Stage 203:============================&gt;                            (1 + 1) / 2]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+--------------------------------------------------------------------------------------+----------+---------+
|industry_name                                                                         |avg_salary|job_count|
+--------------------------------------------------------------------------------------+----------+---------+
|Electronic Computer Manufacturing                                                     |167149.21 |40       |
|Computer Systems Design Services                                                      |132626.29 |2032     |
|Other Computer Related Services                                                       |128829.8  |293      |
|Computing Infrastructure Providers, Data Processing, Web Hosting, and Related Services|118758.05 |294      |
|Custom Computer Programming Services                                                  |116846.93 |1213     |
+--------------------------------------------------------------------------------------+----------+---------+
</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 211:&gt;                                                        (0 + 1) / 1][Stage 211:&gt;  (0 + 1) / 1][Stage 212:&gt;  (0 + 1) / 1][Stage 213:&gt;  (0 + 0) / 1][Stage 212:&gt;                (0 + 1) / 1][Stage 213:&gt;                (0 + 1) / 1][Stage 213:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 213:&gt;                                                        (0 + 1) / 1][Stage 213:&gt;                (0 + 1) / 1][Stage 219:&gt;                (0 + 1) / 1][Stage 219:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 219:&gt;                                                        (0 + 1) / 1][Stage 223:&gt;                                                        (0 + 2) / 3][Stage 223:===================&gt;                                     (1 + 2) / 3][Stage 223:======================================&gt;                  (2 + 1) / 3]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="19">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">industry_name</th>
<th data-quarto-table-cell-role="th">avg_salary</th>
<th data-quarto-table-cell-role="th">job_count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Electronic Computer Manufacturing</td>
<td>167149.21</td>
<td>40</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Computer Systems Design Services</td>
<td>132626.29</td>
<td>2032</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Other Computer Related Services</td>
<td>128829.80</td>
<td>293</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Computing Infrastructure Providers, Data Proce...</td>
<td>118758.05</td>
<td>294</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Custom Computer Programming Services</td>
<td>116846.93</td>
<td>1213</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="82c96983" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> plotly.express <span class="im">as</span> px</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> textwrap</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>query1_pd[<span class="st">"industry_name"</span>] <span class="op">=</span> query1_pd[<span class="st">"industry_name"</span>].<span class="bu">apply</span>(</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    <span class="kw">lambda</span> x: <span class="st">"&lt;br&gt;"</span>.join(textwrap.wrap(x, width<span class="op">=</span><span class="dv">40</span>))</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> px.bar(query1_pd,</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="st">"avg_salary"</span>,</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span><span class="st">"industry_name"</span>,</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"industry_name"</span>,</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>    orientation<span class="op">=</span><span class="st">"h"</span>,</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="st">"Average Salary by Tech Industry (NAICS 2022)"</span>,</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>    labels<span class="op">=</span>{<span class="st">"avg_salary"</span>: <span class="st">"Average Salary (USD)"</span>, <span class="st">"industry_name"</span>: <span class="st">"Industry"</span>},</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>    color_discrete_sequence<span class="op">=</span>px.colors.qualitative.Set2)</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>fig.update_layout(</span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a>    showlegend<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>    margin<span class="op">=</span><span class="bu">dict</span>(l<span class="op">=</span><span class="dv">350</span>, r<span class="op">=</span><span class="dv">100</span>, t<span class="op">=</span><span class="dv">80</span>, b<span class="op">=</span><span class="dv">50</span>),</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a>    yaxis<span class="op">=</span><span class="bu">dict</span>(tickfont<span class="op">=</span><span class="bu">dict</span>(size<span class="op">=</span><span class="dv">11</span>)),</span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a>    xaxis<span class="op">=</span><span class="bu">dict</span>(<span class="bu">range</span><span class="op">=</span>[<span class="dv">0</span>, <span class="dv">200000</span>], tickformat<span class="op">=</span><span class="st">"$,.0f"</span>),</span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a>    height<span class="op">=</span><span class="dv">400</span></span>
<span id="cb29-23"><a href="#cb29-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-24"><a href="#cb29-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-25"><a href="#cb29-25" aria-hidden="true" tabindex="-1"></a>fig.update_traces(</span>
<span id="cb29-26"><a href="#cb29-26" aria-hidden="true" tabindex="-1"></a>    texttemplate<span class="op">=</span><span class="st">"%{x:$,.0f}"</span>,</span>
<span id="cb29-27"><a href="#cb29-27" aria-hidden="true" tabindex="-1"></a>    textposition<span class="op">=</span><span class="st">"outside"</span></span>
<span id="cb29-28"><a href="#cb29-28" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-29"><a href="#cb29-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-30"><a href="#cb29-30" aria-hidden="true" tabindex="-1"></a>fig.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div style="height:400px; width:100%;">            <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>
        <script charset="utf-8" src="https://cdn.plot.ly/plotly-3.6.0.min.js" integrity="sha256-QaOVwtVY0T02VaHrr6pnoHLCwayMJp4O5n4YyaE3rJk=" crossorigin="anonymous"></script>                <div id="a2ad815d-c6d5-4c72-b17b-0aaf4891c50d" class="plotly-graph-div" style="height:100%; width:100%;"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById("a2ad815d-c6d5-4c72-b17b-0aaf4891c50d")) {                    Plotly.newPlot(                        "a2ad815d-c6d5-4c72-b17b-0aaf4891c50d",                        [{"hovertemplate":"Industry=%{y}\u003cbr\u003eAverage Salary (USD)=%{x}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"Electronic Computer Manufacturing","marker":{"color":"rgb(102,194,165)","pattern":{"shape":""}},"name":"Electronic Computer Manufacturing","orientation":"h","showlegend":true,"textposition":"outside","x":{"dtype":"f8","bdata":"4XoUrmlnBEE="},"xaxis":"x","y":["Electronic Computer Manufacturing"],"yaxis":"y","type":"bar","texttemplate":"%{x:$,.0f}"},{"hovertemplate":"Industry=%{y}\u003cbr\u003eAverage Salary (USD)=%{x}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"Computer Systems Design Services","marker":{"color":"rgb(252,141,98)","pattern":{"shape":""}},"name":"Computer Systems Design Services","orientation":"h","showlegend":true,"textposition":"outside","x":{"dtype":"f8","bdata":"H4XrUZIwAEE="},"xaxis":"x","y":["Computer Systems Design Services"],"yaxis":"y","type":"bar","texttemplate":"%{x:$,.0f}"},{"hovertemplate":"Industry=%{y}\u003cbr\u003eAverage Salary (USD)=%{x}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"Other Computer Related Services","marker":{"color":"rgb(141,160,203)","pattern":{"shape":""}},"name":"Other Computer Related Services","orientation":"h","showlegend":true,"textposition":"outside","x":{"dtype":"f8","bdata":"zczMzNxz\u002f0A="},"xaxis":"x","y":["Other Computer Related Services"],"yaxis":"y","type":"bar","texttemplate":"%{x:$,.0f}"},{"hovertemplate":"Industry=%{y}\u003cbr\u003eAverage Salary (USD)=%{x}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"Computing Infrastructure Providers, Data\u003cbr\u003eProcessing, Web Hosting, and Related\u003cbr\u003eServices","marker":{"color":"rgb(231,138,195)","pattern":{"shape":""}},"name":"Computing Infrastructure Providers, Data\u003cbr\u003eProcessing, Web Hosting, and Related\u003cbr\u003eServices","orientation":"h","showlegend":true,"textposition":"outside","x":{"dtype":"f8","bdata":"zczMzGD+\u002fEA="},"xaxis":"x","y":["Computing Infrastructure Providers, Data\u003cbr\u003eProcessing, Web Hosting, and Related\u003cbr\u003eServices"],"yaxis":"y","type":"bar","texttemplate":"%{x:$,.0f}"},{"hovertemplate":"Industry=%{y}\u003cbr\u003eAverage Salary (USD)=%{x}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"Custom Computer Programming Services","marker":{"color":"rgb(166,216,84)","pattern":{"shape":""}},"name":"Custom Computer Programming Services","orientation":"h","showlegend":true,"textposition":"outside","x":{"dtype":"f8","bdata":"FK5H4e6G\u002fEA="},"xaxis":"x","y":["Custom Computer Programming Services"],"yaxis":"y","type":"bar","texttemplate":"%{x:$,.0f}"}],                        {"template":{"data":{"histogram2dcontour":[{"type":"histogram2dcontour","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"choropleth":[{"type":"choropleth","colorbar":{"outlinewidth":0,"ticks":""}}],"histogram2d":[{"type":"histogram2d","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"heatmap":[{"type":"heatmap","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"contourcarpet":[{"type":"contourcarpet","colorbar":{"outlinewidth":0,"ticks":""}}],"contour":[{"type":"contour","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"surface":[{"type":"surface","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"mesh3d":[{"type":"mesh3d","colorbar":{"outlinewidth":0,"ticks":""}}],"scatter":[{"fillpattern":{"fillmode":"overlay","size":10,"solidity":0.2},"type":"scatter"}],"parcoords":[{"type":"parcoords","line":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterpolargl":[{"type":"scatterpolargl","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"bar":[{"error_x":{"color":"#2a3f5f"},"error_y":{"color":"#2a3f5f"},"marker":{"line":{"color":"#E5ECF6","width":0.5},"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"bar"}],"scattergeo":[{"type":"scattergeo","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterpolar":[{"type":"scatterpolar","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"histogram":[{"marker":{"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"histogram"}],"scattergl":[{"type":"scattergl","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatter3d":[{"type":"scatter3d","line":{"colorbar":{"outlinewidth":0,"ticks":""}},"marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattermap":[{"type":"scattermap","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattermapbox":[{"type":"scattermapbox","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterternary":[{"type":"scatterternary","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattercarpet":[{"type":"scattercarpet","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"carpet":[{"aaxis":{"endlinecolor":"#2a3f5f","gridcolor":"white","linecolor":"white","minorgridcolor":"white","startlinecolor":"#2a3f5f"},"baxis":{"endlinecolor":"#2a3f5f","gridcolor":"white","linecolor":"white","minorgridcolor":"white","startlinecolor":"#2a3f5f"},"type":"carpet"}],"table":[{"cells":{"fill":{"color":"#EBF0F8"},"line":{"color":"white"}},"header":{"fill":{"color":"#C8D4E3"},"line":{"color":"white"}},"type":"table"}],"barpolar":[{"marker":{"line":{"color":"#E5ECF6","width":0.5},"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"barpolar"}],"pie":[{"automargin":true,"type":"pie"}]},"layout":{"autotypenumbers":"strict","colorway":["#636efa","#EF553B","#00cc96","#ab63fa","#FFA15A","#19d3f3","#FF6692","#B6E880","#FF97FF","#FECB52"],"font":{"color":"#2a3f5f"},"hovermode":"closest","hoverlabel":{"align":"left"},"paper_bgcolor":"white","plot_bgcolor":"#E5ECF6","polar":{"bgcolor":"#E5ECF6","angularaxis":{"gridcolor":"white","linecolor":"white","ticks":""},"radialaxis":{"gridcolor":"white","linecolor":"white","ticks":""}},"ternary":{"bgcolor":"#E5ECF6","aaxis":{"gridcolor":"white","linecolor":"white","ticks":""},"baxis":{"gridcolor":"white","linecolor":"white","ticks":""},"caxis":{"gridcolor":"white","linecolor":"white","ticks":""}},"coloraxis":{"colorbar":{"outlinewidth":0,"ticks":""}},"colorscale":{"sequential":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]],"sequentialminus":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]],"diverging":[[0,"#8e0152"],[0.1,"#c51b7d"],[0.2,"#de77ae"],[0.3,"#f1b6da"],[0.4,"#fde0ef"],[0.5,"#f7f7f7"],[0.6,"#e6f5d0"],[0.7,"#b8e186"],[0.8,"#7fbc41"],[0.9,"#4d9221"],[1,"#276419"]]},"xaxis":{"gridcolor":"white","linecolor":"white","ticks":"","title":{"standoff":15},"zerolinecolor":"white","automargin":true,"zerolinewidth":2},"yaxis":{"gridcolor":"white","linecolor":"white","ticks":"","title":{"standoff":15},"zerolinecolor":"white","automargin":true,"zerolinewidth":2},"scene":{"xaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2},"yaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2},"zaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2}},"shapedefaults":{"line":{"color":"#2a3f5f"}},"annotationdefaults":{"arrowcolor":"#2a3f5f","arrowhead":0,"arrowwidth":1},"geo":{"bgcolor":"white","landcolor":"#E5ECF6","subunitcolor":"white","showland":true,"showlakes":true,"lakecolor":"white"},"title":{"x":0.05},"mapbox":{"style":"light"},"margin":{"b":0,"l":0,"r":0,"t":30}}},"xaxis":{"anchor":"y","domain":[0.0,1.0],"title":{"text":"Average Salary (USD)"},"range":[0,200000],"tickformat":"$,.0f"},"yaxis":{"anchor":"x","domain":[0.0,1.0],"title":{"text":"Industry"},"categoryorder":"array","categoryarray":["Custom Computer Programming Services","Computing Infrastructure Providers, Data\u003cbr\u003eProcessing, Web Hosting, and Related\u003cbr\u003eServices","Other Computer Related Services","Computer Systems Design Services","Electronic Computer Manufacturing"],"tickfont":{"size":11}},"legend":{"title":{"text":"Industry"},"tracegroupgap":0},"title":{"text":"Average Salary by Tech Industry (NAICS 2022)"},"barmode":"relative","margin":{"l":350,"r":100,"t":80,"b":50},"showlegend":false,"height":400},                        {"responsive": true}                    ).then(function(){
                            
var gd = document.getElementById('a2ad815d-c6d5-4c72-b17b-0aaf4891c50d');
var x = new MutationObserver(function (mutations, observer) {{
        var display = window.getComputedStyle(gd).display;
        if (!display || display === 'none') {{
            console.log([gd, 'removed!']);
            Plotly.purge(gd);
            observer.disconnect();
        }}
}});

// Listen for the removal of the full notebook cells
var notebookContainer = gd.closest('#notebook-container');
if (notebookContainer) {{
    x.observe(notebookContainer, {childList: true});
}}

// Listen for the clearing of the current output cell
var outputEl = gd.closest('.output');
if (outputEl) {{
    x.observe(outputEl, {childList: true});
}}

                        })                };            </script>        </div>
</div>
</div>
<p><strong>Insight:</strong> Electronic Computer Manufacturing ($167,149) offers the highest average salary among tech industries, significantly higher than Custom Computer Programming Services ($116,847). This suggests hardware manufacturing roles command premium compensation compared to software services, likely due to specialized skills and lower job volume.</p>
</section>
<section id="query-2-top-companies-with-most-remote-jobs-in-california-washington-and-new-york" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="query-2-top-companies-with-most-remote-jobs-in-california-washington-and-new-york"><span class="header-section-number">3.3</span> Query 2: Top Companies with Most Remote Jobs in California, Washington and New York</h3>
<div id="2efaf122" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>query2 <span class="op">=</span> spark.sql(<span class="st">"""</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="st">    SELECT </span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="st">        c.COMPANY_NAME AS company_name,</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="st">        l.STATE_NAME AS state,</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="st">        COUNT(DISTINCT j.ID) AS remote_jobs</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="st">    FROM job_postings j</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="st">    JOIN companies c ON j.company_id = c.company_id</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="st">    JOIN locations l ON j.location_id = l.location_id</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="st">    WHERE j.REMOTE_TYPE_NAME = 'Remote'</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="st">    AND l.STATE_NAME IN ('California', 'Washington', 'New York')</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="st">    AND c.COMPANY_NAME != 'Unclassified'</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a><span class="st">    GROUP BY c.COMPANY_NAME, l.STATE_NAME</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a><span class="st">    ORDER BY remote_jobs DESC</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a><span class="st">    LIMIT 15</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span>)</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>query2.show(truncate<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>query2_pd <span class="op">=</span> query2.toPandas()</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>query2_pd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 240:&gt;  (0 + 1) / 1][Stage 241:&gt;  (0 + 1) / 1][Stage 242:&gt;  (0 + 0) / 1][Stage 241:&gt;                (0 + 1) / 1][Stage 242:&gt;                (0 + 1) / 1][Stage 242:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 242:&gt;                (0 + 1) / 1][Stage 248:&gt;                (0 + 1) / 1][Stage 248:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 248:&gt;                                                        (0 + 1) / 1][Stage 253:&gt;                                                        (0 + 2) / 2][Stage 253:============================&gt;                            (1 + 1) / 2]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+----------------------------------------------+----------+-----------+
|company_name                                  |state     |remote_jobs|
+----------------------------------------------+----------+-----------+
|Kaiser Permanente                             |California|33         |
|University of California                      |California|23         |
|The Judge Group                               |New York  |23         |
|The Judge Group                               |California|21         |
|BCforward                                     |Washington|18         |
|Providence                                    |Washington|15         |
|Visions Federal Credit Union                  |New York  |14         |
|Providence                                    |California|13         |
|State of New York                             |New York  |13         |
|Cognizant Technology Solutions                |California|12         |
|State of Washington                           |Washington|12         |
|California Public Employees' Retirement System|California|12         |
|Fisher Investments                            |Washington|11         |
|Baer Group                                    |California|10         |
|Central California Alliance For Health        |California|10         |
+----------------------------------------------+----------+-----------+
</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 261:&gt;                (0 + 1) / 1][Stage 262:&gt;                (0 + 1) / 1][Stage 261:&gt;  (0 + 1) / 1][Stage 262:&gt;  (0 + 1) / 1][Stage 263:&gt;  (0 + 0) / 1][Stage 263:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 263:&gt;                (0 + 1) / 1][Stage 270:&gt;                (0 + 1) / 1][Stage 270:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 270:&gt;                                                        (0 + 1) / 1][Stage 274:&gt;                                                        (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="21">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">company_name</th>
<th data-quarto-table-cell-role="th">state</th>
<th data-quarto-table-cell-role="th">remote_jobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>Kaiser Permanente</td>
<td>California</td>
<td>33</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>University of California</td>
<td>California</td>
<td>23</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>The Judge Group</td>
<td>New York</td>
<td>23</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>The Judge Group</td>
<td>California</td>
<td>21</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>BCforward</td>
<td>Washington</td>
<td>18</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Providence</td>
<td>Washington</td>
<td>15</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>Visions Federal Credit Union</td>
<td>New York</td>
<td>14</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>Providence</td>
<td>California</td>
<td>13</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>State of New York</td>
<td>New York</td>
<td>13</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>California Public Employees' Retirement System</td>
<td>California</td>
<td>12</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>State of Washington</td>
<td>Washington</td>
<td>12</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>Cognizant Technology Solutions</td>
<td>California</td>
<td>12</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>Fisher Investments</td>
<td>Washington</td>
<td>11</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>Central California Alliance For Health</td>
<td>California</td>
<td>10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>Baer Group</td>
<td>California</td>
<td>10</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="f5ef7135" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>query2_pd_sorted <span class="op">=</span> query2_pd.sort_values([<span class="st">"company_name"</span>, <span class="st">"state"</span>])</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> px.bar(query2_pd_sorted,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="st">"remote_jobs"</span>,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span><span class="st">"company_name"</span>,</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"state"</span>,</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    barmode<span class="op">=</span><span class="st">"group"</span>,</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>    orientation<span class="op">=</span><span class="st">"h"</span>,</span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="st">"Top Companies with Remote Jobs in California, Washington and New York&lt;br&gt;(June - September 2024)"</span>,</span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>    labels<span class="op">=</span>{<span class="st">"company_name"</span>: <span class="st">"Company"</span>, <span class="st">"remote_jobs"</span>: <span class="st">"Remote Job Postings"</span>, <span class="st">"state"</span>: <span class="st">"State"</span>},</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a>    color_discrete_sequence<span class="op">=</span>px.colors.qualitative.Set2)</span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>fig.update_layout(</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>    margin<span class="op">=</span><span class="bu">dict</span>(l<span class="op">=</span><span class="dv">300</span>, r<span class="op">=</span><span class="dv">100</span>, t<span class="op">=</span><span class="dv">100</span>, b<span class="op">=</span><span class="dv">50</span>),</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>    height<span class="op">=</span><span class="dv">550</span>,</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>    yaxis<span class="op">=</span><span class="bu">dict</span>(tickfont<span class="op">=</span><span class="bu">dict</span>(size<span class="op">=</span><span class="dv">11</span>))</span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a>fig.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div style="height:550px; width:100%;">            <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>
        <script charset="utf-8" src="https://cdn.plot.ly/plotly-3.6.0.min.js" integrity="sha256-QaOVwtVY0T02VaHrr6pnoHLCwayMJp4O5n4YyaE3rJk=" crossorigin="anonymous"></script>                <div id="97a52331-ebd5-488a-a78d-be5d4873779c" class="plotly-graph-div" style="height:100%; width:100%;"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById("97a52331-ebd5-488a-a78d-be5d4873779c")) {                    Plotly.newPlot(                        "97a52331-ebd5-488a-a78d-be5d4873779c",                        [{"alignmentgroup":"True","hovertemplate":"State=Washington\u003cbr\u003eRemote Job Postings=%{x}\u003cbr\u003eCompany=%{y}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"Washington","marker":{"color":"rgb(102,194,165)","pattern":{"shape":""}},"name":"Washington","offsetgroup":"Washington","orientation":"h","showlegend":true,"textposition":"auto","x":{"dtype":"i1","bdata":"EgsPDA=="},"xaxis":"x","y":["BCforward","Fisher Investments","Providence","State of Washington"],"yaxis":"y","type":"bar"},{"alignmentgroup":"True","hovertemplate":"State=California\u003cbr\u003eRemote Job Postings=%{x}\u003cbr\u003eCompany=%{y}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"California","marker":{"color":"rgb(252,141,98)","pattern":{"shape":""}},"name":"California","offsetgroup":"California","orientation":"h","showlegend":true,"textposition":"auto","x":{"dtype":"i1","bdata":"CgwKDCENFRc="},"xaxis":"x","y":["Baer Group","California Public Employees' Retirement System","Central California Alliance For Health","Cognizant Technology Solutions","Kaiser Permanente","Providence","The Judge Group","University of California"],"yaxis":"y","type":"bar"},{"alignmentgroup":"True","hovertemplate":"State=New York\u003cbr\u003eRemote Job Postings=%{x}\u003cbr\u003eCompany=%{y}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"New York","marker":{"color":"rgb(141,160,203)","pattern":{"shape":""}},"name":"New York","offsetgroup":"New York","orientation":"h","showlegend":true,"textposition":"auto","x":{"dtype":"i1","bdata":"DRcO"},"xaxis":"x","y":["State of New York","The Judge Group","Visions Federal Credit Union"],"yaxis":"y","type":"bar"}],                        {"template":{"data":{"histogram2dcontour":[{"type":"histogram2dcontour","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"choropleth":[{"type":"choropleth","colorbar":{"outlinewidth":0,"ticks":""}}],"histogram2d":[{"type":"histogram2d","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"heatmap":[{"type":"heatmap","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"contourcarpet":[{"type":"contourcarpet","colorbar":{"outlinewidth":0,"ticks":""}}],"contour":[{"type":"contour","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"surface":[{"type":"surface","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"mesh3d":[{"type":"mesh3d","colorbar":{"outlinewidth":0,"ticks":""}}],"scatter":[{"fillpattern":{"fillmode":"overlay","size":10,"solidity":0.2},"type":"scatter"}],"parcoords":[{"type":"parcoords","line":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterpolargl":[{"type":"scatterpolargl","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"bar":[{"error_x":{"color":"#2a3f5f"},"error_y":{"color":"#2a3f5f"},"marker":{"line":{"color":"#E5ECF6","width":0.5},"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"bar"}],"scattergeo":[{"type":"scattergeo","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterpolar":[{"type":"scatterpolar","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"histogram":[{"marker":{"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"histogram"}],"scattergl":[{"type":"scattergl","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatter3d":[{"type":"scatter3d","line":{"colorbar":{"outlinewidth":0,"ticks":""}},"marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattermap":[{"type":"scattermap","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattermapbox":[{"type":"scattermapbox","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterternary":[{"type":"scatterternary","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattercarpet":[{"type":"scattercarpet","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"carpet":[{"aaxis":{"endlinecolor":"#2a3f5f","gridcolor":"white","linecolor":"white","minorgridcolor":"white","startlinecolor":"#2a3f5f"},"baxis":{"endlinecolor":"#2a3f5f","gridcolor":"white","linecolor":"white","minorgridcolor":"white","startlinecolor":"#2a3f5f"},"type":"carpet"}],"table":[{"cells":{"fill":{"color":"#EBF0F8"},"line":{"color":"white"}},"header":{"fill":{"color":"#C8D4E3"},"line":{"color":"white"}},"type":"table"}],"barpolar":[{"marker":{"line":{"color":"#E5ECF6","width":0.5},"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"barpolar"}],"pie":[{"automargin":true,"type":"pie"}]},"layout":{"autotypenumbers":"strict","colorway":["#636efa","#EF553B","#00cc96","#ab63fa","#FFA15A","#19d3f3","#FF6692","#B6E880","#FF97FF","#FECB52"],"font":{"color":"#2a3f5f"},"hovermode":"closest","hoverlabel":{"align":"left"},"paper_bgcolor":"white","plot_bgcolor":"#E5ECF6","polar":{"bgcolor":"#E5ECF6","angularaxis":{"gridcolor":"white","linecolor":"white","ticks":""},"radialaxis":{"gridcolor":"white","linecolor":"white","ticks":""}},"ternary":{"bgcolor":"#E5ECF6","aaxis":{"gridcolor":"white","linecolor":"white","ticks":""},"baxis":{"gridcolor":"white","linecolor":"white","ticks":""},"caxis":{"gridcolor":"white","linecolor":"white","ticks":""}},"coloraxis":{"colorbar":{"outlinewidth":0,"ticks":""}},"colorscale":{"sequential":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]],"sequentialminus":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]],"diverging":[[0,"#8e0152"],[0.1,"#c51b7d"],[0.2,"#de77ae"],[0.3,"#f1b6da"],[0.4,"#fde0ef"],[0.5,"#f7f7f7"],[0.6,"#e6f5d0"],[0.7,"#b8e186"],[0.8,"#7fbc41"],[0.9,"#4d9221"],[1,"#276419"]]},"xaxis":{"gridcolor":"white","linecolor":"white","ticks":"","title":{"standoff":15},"zerolinecolor":"white","automargin":true,"zerolinewidth":2},"yaxis":{"gridcolor":"white","linecolor":"white","ticks":"","title":{"standoff":15},"zerolinecolor":"white","automargin":true,"zerolinewidth":2},"scene":{"xaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2},"yaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2},"zaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2}},"shapedefaults":{"line":{"color":"#2a3f5f"}},"annotationdefaults":{"arrowcolor":"#2a3f5f","arrowhead":0,"arrowwidth":1},"geo":{"bgcolor":"white","landcolor":"#E5ECF6","subunitcolor":"white","showland":true,"showlakes":true,"lakecolor":"white"},"title":{"x":0.05},"mapbox":{"style":"light"},"margin":{"b":0,"l":0,"r":0,"t":30}}},"xaxis":{"anchor":"y","domain":[0.0,1.0],"title":{"text":"Remote Job Postings"}},"yaxis":{"anchor":"x","domain":[0.0,1.0],"title":{"text":"Company"},"tickfont":{"size":11}},"legend":{"title":{"text":"State"},"tracegroupgap":0},"title":{"text":"Top Companies with Remote Jobs in California, Washington and New York\u003cbr\u003e(June - September 2024)"},"barmode":"group","margin":{"l":300,"r":100,"t":100,"b":50},"height":550},                        {"responsive": true}                    ).then(function(){
                            
var gd = document.getElementById('97a52331-ebd5-488a-a78d-be5d4873779c');
var x = new MutationObserver(function (mutations, observer) {{
        var display = window.getComputedStyle(gd).display;
        if (!display || display === 'none') {{
            console.log([gd, 'removed!']);
            Plotly.purge(gd);
            observer.disconnect();
        }}
}});

// Listen for the removal of the full notebook cells
var notebookContainer = gd.closest('#notebook-container');
if (notebookContainer) {{
    x.observe(notebookContainer, {childList: true});
}}

// Listen for the clearing of the current output cell
var outputEl = gd.closest('.output');
if (outputEl) {{
    x.observe(outputEl, {childList: true});
}}

                        })                };            </script>        </div>
</div>
</div>
<p><strong>Insight:</strong> Kaiser Permanente leads remote job postings in California with 33 postings, followed by University of California with 23. Washington state shows strong presence from BCforward and Providence, while New York is represented by The Judge Group. Healthcare and staffing companies dominate remote hiring across all three states.</p>
</section>
<section id="query-3-monthly-job-posting-trends-in-california-washington-and-new-york" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="query-3-monthly-job-posting-trends-in-california-washington-and-new-york"><span class="header-section-number">3.4</span> Query 3: Monthly Job Posting Trends in California, Washington and New York</h3>
<div id="8a89258f" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>query3 <span class="op">=</span> spark.sql(<span class="st">"""</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="st">    SELECT </span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="st">        YEAR(to_date(j.POSTED, 'M/d/yyyy')) AS year,</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="st">        MONTH(to_date(j.POSTED, 'M/d/yyyy')) AS month,</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="st">        l.STATE_NAME AS state,</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="st">        COUNT(DISTINCT j.ID) AS job_count</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="st">    FROM job_postings j</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="st">    JOIN locations l ON j.location_id = l.location_id</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="st">    WHERE l.STATE_NAME IN ('California', 'Washington', 'New York')</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a><span class="st">    AND to_date(j.POSTED, 'M/d/yyyy') IS NOT NULL</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a><span class="st">    GROUP BY year, month, l.STATE_NAME</span></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a><span class="st">    ORDER BY year ASC, month ASC</span></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span>)</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a>query3.show(truncate<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a>query3_pd <span class="op">=</span> query3.toPandas()</span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>query3_pd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 282:&gt;  (0 + 1) / 1][Stage 283:&gt;  (0 + 1) / 1][Stage 284:&gt;  (0 + 0) / 1][Stage 284:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 284:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 292:&gt;                                                        (0 + 1) / 1][Stage 292:&gt;                                                        (0 + 1) / 1][Stage 292:&gt;                                                        (0 + 1) / 1][Stage 292:&gt;                                                        (0 + 1) / 1][Stage 292:&gt;                                                        (0 + 1) / 1]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+----+-----+----------+---------+
|year|month|state     |job_count|
+----+-----+----------+---------+
|2024|5    |New York  |662      |
|2024|5    |Washington|325      |
|2024|5    |California|1477     |
|2024|6    |Washington|373      |
|2024|6    |California|1368     |
|2024|6    |New York  |627      |
|2024|7    |New York  |591      |
|2024|7    |Washington|267      |
|2024|7    |California|1251     |
|2024|8    |California|1409     |
|2024|8    |New York  |733      |
|2024|8    |Washington|329      |
|2024|9    |Washington|330      |
|2024|9    |New York  |728      |
|2024|9    |California|1579     |
+----+-----+----------+---------+
</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 298:&gt;                                                        (0 + 1) / 1][Stage 298:&gt;  (0 + 1) / 1][Stage 299:&gt;  (0 + 1) / 1][Stage 300:&gt;  (0 + 0) / 1][Stage 299:&gt;                (0 + 1) / 1][Stage 300:&gt;                (0 + 1) / 1][Stage 300:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 300:&gt;                (0 + 1) / 1][Stage 306:&gt;                (0 + 1) / 1][Stage 306:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 306:&gt;                                                        (0 + 1) / 1][Stage 310:&gt;                                                        (0 + 2) / 2][Stage 310:============================&gt;                            (1 + 1) / 2][Stage 310:============================&gt;                            (1 + 1) / 2][Stage 310:============================&gt;                            (1 + 1) / 2][Stage 310:============================&gt;                            (1 + 1) / 2]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="23">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">year</th>
<th data-quarto-table-cell-role="th">month</th>
<th data-quarto-table-cell-role="th">state</th>
<th data-quarto-table-cell-role="th">job_count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>2024</td>
<td>5</td>
<td>New York</td>
<td>662</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>2024</td>
<td>5</td>
<td>Washington</td>
<td>325</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>2024</td>
<td>5</td>
<td>California</td>
<td>1477</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>2024</td>
<td>6</td>
<td>Washington</td>
<td>373</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>2024</td>
<td>6</td>
<td>California</td>
<td>1368</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>2024</td>
<td>6</td>
<td>New York</td>
<td>627</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>2024</td>
<td>7</td>
<td>New York</td>
<td>591</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>2024</td>
<td>7</td>
<td>Washington</td>
<td>267</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>2024</td>
<td>7</td>
<td>California</td>
<td>1251</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>2024</td>
<td>8</td>
<td>California</td>
<td>1409</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>2024</td>
<td>8</td>
<td>New York</td>
<td>733</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>2024</td>
<td>8</td>
<td>Washington</td>
<td>329</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>2024</td>
<td>9</td>
<td>Washington</td>
<td>330</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>2024</td>
<td>9</td>
<td>New York</td>
<td>728</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>2024</td>
<td>9</td>
<td>California</td>
<td>1579</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="b706b812" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>query3_pd[<span class="st">"month_year"</span>] <span class="op">=</span> query3_pd[<span class="st">"month"</span>].astype(<span class="bu">str</span>) <span class="op">+</span> <span class="st">"/"</span> <span class="op">+</span> query3_pd[<span class="st">"year"</span>].astype(<span class="bu">str</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> px.line(query3_pd,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="st">"month_year"</span>,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span><span class="st">"job_count"</span>,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"state"</span>,</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="st">"Monthly Job Posting Trends in California, Washington and New York&lt;br&gt;(June - September 2024)"</span>,</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>    labels<span class="op">=</span>{<span class="st">"month_year"</span>: <span class="st">"Month/Year"</span>, <span class="st">"job_count"</span>: <span class="st">"Job Postings"</span>, <span class="st">"state"</span>: <span class="st">"State"</span>},</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>    markers<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>    color_discrete_sequence<span class="op">=</span>px.colors.qualitative.Set2)</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>fig.update_layout(</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>    margin<span class="op">=</span><span class="bu">dict</span>(l<span class="op">=</span><span class="dv">50</span>, r<span class="op">=</span><span class="dv">50</span>, t<span class="op">=</span><span class="dv">100</span>, b<span class="op">=</span><span class="dv">50</span>),</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>    height<span class="op">=</span><span class="dv">450</span></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>fig.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div style="height:450px; width:100%;">            <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>
        <script charset="utf-8" src="https://cdn.plot.ly/plotly-3.6.0.min.js" integrity="sha256-QaOVwtVY0T02VaHrr6pnoHLCwayMJp4O5n4YyaE3rJk=" crossorigin="anonymous"></script>                <div id="91c7f8cb-a884-4975-86b0-a967c2cfeea6" class="plotly-graph-div" style="height:100%; width:100%;"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById("91c7f8cb-a884-4975-86b0-a967c2cfeea6")) {                    Plotly.newPlot(                        "91c7f8cb-a884-4975-86b0-a967c2cfeea6",                        [{"hovertemplate":"State=New York\u003cbr\u003eMonth\u002fYear=%{x}\u003cbr\u003eJob Postings=%{y}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"New York","line":{"color":"rgb(102,194,165)","dash":"solid"},"marker":{"symbol":"circle"},"mode":"lines+markers","name":"New York","orientation":"v","showlegend":true,"x":["5\u002f2024","6\u002f2024","7\u002f2024","8\u002f2024","9\u002f2024"],"xaxis":"x","y":{"dtype":"i2","bdata":"lgJzAk8C3QLYAg=="},"yaxis":"y","type":"scatter"},{"hovertemplate":"State=Washington\u003cbr\u003eMonth\u002fYear=%{x}\u003cbr\u003eJob Postings=%{y}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"Washington","line":{"color":"rgb(252,141,98)","dash":"solid"},"marker":{"symbol":"circle"},"mode":"lines+markers","name":"Washington","orientation":"v","showlegend":true,"x":["5\u002f2024","6\u002f2024","7\u002f2024","8\u002f2024","9\u002f2024"],"xaxis":"x","y":{"dtype":"i2","bdata":"RQF1AQsBSQFKAQ=="},"yaxis":"y","type":"scatter"},{"hovertemplate":"State=California\u003cbr\u003eMonth\u002fYear=%{x}\u003cbr\u003eJob Postings=%{y}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"California","line":{"color":"rgb(141,160,203)","dash":"solid"},"marker":{"symbol":"circle"},"mode":"lines+markers","name":"California","orientation":"v","showlegend":true,"x":["5\u002f2024","6\u002f2024","7\u002f2024","8\u002f2024","9\u002f2024"],"xaxis":"x","y":{"dtype":"i2","bdata":"xQVYBeMEgQUrBg=="},"yaxis":"y","type":"scatter"}],                        {"template":{"data":{"histogram2dcontour":[{"type":"histogram2dcontour","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"choropleth":[{"type":"choropleth","colorbar":{"outlinewidth":0,"ticks":""}}],"histogram2d":[{"type":"histogram2d","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"heatmap":[{"type":"heatmap","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"contourcarpet":[{"type":"contourcarpet","colorbar":{"outlinewidth":0,"ticks":""}}],"contour":[{"type":"contour","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"surface":[{"type":"surface","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"mesh3d":[{"type":"mesh3d","colorbar":{"outlinewidth":0,"ticks":""}}],"scatter":[{"fillpattern":{"fillmode":"overlay","size":10,"solidity":0.2},"type":"scatter"}],"parcoords":[{"type":"parcoords","line":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterpolargl":[{"type":"scatterpolargl","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"bar":[{"error_x":{"color":"#2a3f5f"},"error_y":{"color":"#2a3f5f"},"marker":{"line":{"color":"#E5ECF6","width":0.5},"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"bar"}],"scattergeo":[{"type":"scattergeo","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterpolar":[{"type":"scatterpolar","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"histogram":[{"marker":{"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"histogram"}],"scattergl":[{"type":"scattergl","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatter3d":[{"type":"scatter3d","line":{"colorbar":{"outlinewidth":0,"ticks":""}},"marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattermap":[{"type":"scattermap","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattermapbox":[{"type":"scattermapbox","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterternary":[{"type":"scatterternary","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattercarpet":[{"type":"scattercarpet","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"carpet":[{"aaxis":{"endlinecolor":"#2a3f5f","gridcolor":"white","linecolor":"white","minorgridcolor":"white","startlinecolor":"#2a3f5f"},"baxis":{"endlinecolor":"#2a3f5f","gridcolor":"white","linecolor":"white","minorgridcolor":"white","startlinecolor":"#2a3f5f"},"type":"carpet"}],"table":[{"cells":{"fill":{"color":"#EBF0F8"},"line":{"color":"white"}},"header":{"fill":{"color":"#C8D4E3"},"line":{"color":"white"}},"type":"table"}],"barpolar":[{"marker":{"line":{"color":"#E5ECF6","width":0.5},"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"barpolar"}],"pie":[{"automargin":true,"type":"pie"}]},"layout":{"autotypenumbers":"strict","colorway":["#636efa","#EF553B","#00cc96","#ab63fa","#FFA15A","#19d3f3","#FF6692","#B6E880","#FF97FF","#FECB52"],"font":{"color":"#2a3f5f"},"hovermode":"closest","hoverlabel":{"align":"left"},"paper_bgcolor":"white","plot_bgcolor":"#E5ECF6","polar":{"bgcolor":"#E5ECF6","angularaxis":{"gridcolor":"white","linecolor":"white","ticks":""},"radialaxis":{"gridcolor":"white","linecolor":"white","ticks":""}},"ternary":{"bgcolor":"#E5ECF6","aaxis":{"gridcolor":"white","linecolor":"white","ticks":""},"baxis":{"gridcolor":"white","linecolor":"white","ticks":""},"caxis":{"gridcolor":"white","linecolor":"white","ticks":""}},"coloraxis":{"colorbar":{"outlinewidth":0,"ticks":""}},"colorscale":{"sequential":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]],"sequentialminus":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]],"diverging":[[0,"#8e0152"],[0.1,"#c51b7d"],[0.2,"#de77ae"],[0.3,"#f1b6da"],[0.4,"#fde0ef"],[0.5,"#f7f7f7"],[0.6,"#e6f5d0"],[0.7,"#b8e186"],[0.8,"#7fbc41"],[0.9,"#4d9221"],[1,"#276419"]]},"xaxis":{"gridcolor":"white","linecolor":"white","ticks":"","title":{"standoff":15},"zerolinecolor":"white","automargin":true,"zerolinewidth":2},"yaxis":{"gridcolor":"white","linecolor":"white","ticks":"","title":{"standoff":15},"zerolinecolor":"white","automargin":true,"zerolinewidth":2},"scene":{"xaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2},"yaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2},"zaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2}},"shapedefaults":{"line":{"color":"#2a3f5f"}},"annotationdefaults":{"arrowcolor":"#2a3f5f","arrowhead":0,"arrowwidth":1},"geo":{"bgcolor":"white","landcolor":"#E5ECF6","subunitcolor":"white","showland":true,"showlakes":true,"lakecolor":"white"},"title":{"x":0.05},"mapbox":{"style":"light"},"margin":{"b":0,"l":0,"r":0,"t":30}}},"xaxis":{"anchor":"y","domain":[0.0,1.0],"title":{"text":"Month\u002fYear"}},"yaxis":{"anchor":"x","domain":[0.0,1.0],"title":{"text":"Job Postings"}},"legend":{"title":{"text":"State"},"tracegroupgap":0},"title":{"text":"Monthly Job Posting Trends in California, Washington and New York\u003cbr\u003e(June - September 2024)"},"margin":{"l":50,"r":50,"t":100,"b":50},"height":450},                        {"responsive": true}                    ).then(function(){
                            
var gd = document.getElementById('91c7f8cb-a884-4975-86b0-a967c2cfeea6');
var x = new MutationObserver(function (mutations, observer) {{
        var display = window.getComputedStyle(gd).display;
        if (!display || display === 'none') {{
            console.log([gd, 'removed!']);
            Plotly.purge(gd);
            observer.disconnect();
        }}
}});

// Listen for the removal of the full notebook cells
var notebookContainer = gd.closest('#notebook-container');
if (notebookContainer) {{
    x.observe(notebookContainer, {childList: true});
}}

// Listen for the clearing of the current output cell
var outputEl = gd.closest('.output');
if (outputEl) {{
    x.observe(outputEl, {childList: true});
}}

                        })                };            </script>        </div>
</div>
</div>
<p><strong>Insight:</strong> California consistently dominates job postings across all months, peaking in June 2024. Both California and Washington show a dip in August before recovering slightly in September. New York shows steady but lower posting volume compared to California throughout the period.</p>
</section>
<section id="query-4-salary-comparisons-across-major-us-cities" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="query-4-salary-comparisons-across-major-us-cities"><span class="header-section-number">3.5</span> Query 4: Salary Comparisons Across Major US Cities</h3>
<div id="8cde2ed0" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>query4 <span class="op">=</span> spark.sql(<span class="st">"""</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="st">    SELECT </span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="st">        CASE l.MSA</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="st">            WHEN 14460 THEN 'Boston'</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="st">            WHEN 47900 THEN 'Washington DC'</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="st">            WHEN 35620 THEN 'New York'</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a><span class="st">            WHEN 41860 THEN 'San Francisco'</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="st">            WHEN 42660 THEN 'Seattle'</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="st">            WHEN 31080 THEN 'Los Angeles'</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a><span class="st">            WHEN 19100 THEN 'Dallas'</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a><span class="st">            WHEN 26420 THEN 'Houston'</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a><span class="st">            WHEN 12420 THEN 'Austin'</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a><span class="st">            WHEN 34980 THEN 'Nashville'</span></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a><span class="st">            WHEN 28140 THEN 'Kansas City'</span></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a><span class="st">            WHEN 19740 THEN 'Denver'</span></span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a><span class="st">        END AS city,</span></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a><span class="st">        ROUND(AVG(j.SALARY), 2) AS avg_salary,</span></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a><span class="st">        COUNT(DISTINCT j.ID) AS job_count</span></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a><span class="st">    FROM job_postings j</span></span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a><span class="st">    JOIN locations l ON j.location_id = l.location_id</span></span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a><span class="st">    WHERE j.SALARY IS NOT NULL</span></span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a><span class="st">    AND j.SALARY &gt; 0</span></span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a><span class="st">    AND l.MSA IN (14460, 47900, 35620, 41860, 42660, 31080, 19100, 26420, 12420, 34980, 28140, 19740)</span></span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a><span class="st">    GROUP BY l.MSA</span></span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a><span class="st">    ORDER BY avg_salary DESC</span></span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a><span class="st">"""</span>)</span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a>query4.show(truncate<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb40-29"><a href="#cb40-29" aria-hidden="true" tabindex="-1"></a>query4_pd <span class="op">=</span> query4.toPandas()</span>
<span id="cb40-30"><a href="#cb40-30" aria-hidden="true" tabindex="-1"></a>query4_pd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 327:&gt;  (0 + 1) / 1][Stage 328:&gt;  (0 + 1) / 1][Stage 329:&gt;  (0 + 0) / 1][Stage 328:&gt;                (0 + 1) / 1][Stage 329:&gt;                (0 + 1) / 1]                                                                                [Stage 329:&gt;                (0 + 1) / 1][Stage 334:&gt;                (0 + 1) / 1][Stage 334:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 334:&gt;                                                        (0 + 1) / 1][Stage 339:&gt;                                                        (0 + 2) / 3][Stage 339:===================&gt;                                     (1 + 2) / 3][Stage 339:======================================&gt;                  (2 + 1) / 3]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>+-------------+----------+---------+
|city         |avg_salary|job_count|
+-------------+----------+---------+
|San Francisco|142528.92 |1141     |
|Nashville    |131897.78 |284      |
|Washington DC|130848.1  |1555     |
|Seattle      |130489.97 |761      |
|Houston      |117703.17 |546      |
|Los Angeles  |115446.53 |1438     |
|Boston       |113552.8  |662      |
|New York     |112812.67 |2154     |
|Austin       |110469.2  |547      |
|Dallas       |107710.61 |1223     |
|Denver       |107692.99 |669      |
|Kansas City  |77687.63  |272      |
+-------------+----------+---------+
</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Stage 347:&gt;  (0 + 1) / 1][Stage 348:&gt;  (0 + 1) / 1][Stage 349:&gt;  (0 + 0) / 1][Stage 348:&gt;                (0 + 1) / 1][Stage 349:&gt;                (0 + 1) / 1][Stage 349:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 349:&gt;                                                        (0 + 1) / 1][Stage 349:&gt;                (0 + 1) / 1][Stage 354:&gt;                (0 + 1) / 1][Stage 354:&gt;                                                        (0 + 1) / 1]                                                                                [Stage 354:&gt;                                                        (0 + 1) / 1][Stage 359:&gt;                                                        (0 + 2) / 3][Stage 359:===================&gt;                                     (1 + 2) / 3][Stage 359:======================================&gt;                  (2 + 1) / 3]                                                                                </code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="25">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">city</th>
<th data-quarto-table-cell-role="th">avg_salary</th>
<th data-quarto-table-cell-role="th">job_count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>San Francisco</td>
<td>142528.92</td>
<td>1141</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>Nashville</td>
<td>131897.78</td>
<td>284</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>Washington DC</td>
<td>130848.10</td>
<td>1555</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>Seattle</td>
<td>130489.97</td>
<td>761</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>Houston</td>
<td>117703.17</td>
<td>546</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>Los Angeles</td>
<td>115446.53</td>
<td>1438</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>Boston</td>
<td>113552.80</td>
<td>662</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>New York</td>
<td>112812.67</td>
<td>2154</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>Austin</td>
<td>110469.20</td>
<td>547</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>Dallas</td>
<td>107710.61</td>
<td>1223</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>Denver</td>
<td>107692.99</td>
<td>669</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>Kansas City</td>
<td>77687.63</td>
<td>272</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="a1bfd5e7" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> px.bar(query4_pd,</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>    x<span class="op">=</span><span class="st">"city"</span>,</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span><span class="st">"avg_salary"</span>,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>    color<span class="op">=</span><span class="st">"city"</span>,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="st">"Average Salary Across Major US Cities"</span>,</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>    labels<span class="op">=</span>{<span class="st">"city"</span>: <span class="st">"City"</span>, <span class="st">"avg_salary"</span>: <span class="st">"Average Salary (USD)"</span>},</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>    color_discrete_sequence<span class="op">=</span>px.colors.qualitative.Set2)</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>fig.update_layout(</span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a>    showlegend<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>    xaxis_tickangle<span class="op">=-</span><span class="dv">45</span>,</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>    yaxis<span class="op">=</span><span class="bu">dict</span>(tickformat<span class="op">=</span><span class="st">"$,.0f"</span>),</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>    margin<span class="op">=</span><span class="bu">dict</span>(l<span class="op">=</span><span class="dv">50</span>, r<span class="op">=</span><span class="dv">50</span>, t<span class="op">=</span><span class="dv">80</span>, b<span class="op">=</span><span class="dv">150</span>),</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>    height<span class="op">=</span><span class="dv">500</span></span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a>fig.update_traces(</span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a>    texttemplate<span class="op">=</span><span class="st">"%{y:$,.0f}"</span>,</span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a>    textposition<span class="op">=</span><span class="st">"outside"</span></span>
<span id="cb44-20"><a href="#cb44-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb44-21"><a href="#cb44-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-22"><a href="#cb44-22" aria-hidden="true" tabindex="-1"></a>fig.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div style="height:500px; width:100%;">            <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_SVG"></script><script>if (window.MathJax && window.MathJax.Hub && window.MathJax.Hub.Config) {window.MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}</script>                <script>window.PlotlyConfig = {MathJaxConfig: 'local'};</script>
        <script charset="utf-8" src="https://cdn.plot.ly/plotly-3.6.0.min.js" integrity="sha256-QaOVwtVY0T02VaHrr6pnoHLCwayMJp4O5n4YyaE3rJk=" crossorigin="anonymous"></script>                <div id="92615ddf-a033-45e9-b08e-82e532ac9398" class="plotly-graph-div" style="height:100%; width:100%;"></div>            <script>                window.PLOTLYENV=window.PLOTLYENV || {};                                if (document.getElementById("92615ddf-a033-45e9-b08e-82e532ac9398")) {                    Plotly.newPlot(                        "92615ddf-a033-45e9-b08e-82e532ac9398",                        [{"hovertemplate":"City=%{x}\u003cbr\u003eAverage Salary (USD)=%{y}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"San Francisco","marker":{"color":"rgb(102,194,165)","pattern":{"shape":""}},"name":"San Francisco","orientation":"v","showlegend":true,"textposition":"outside","x":["San Francisco"],"xaxis":"x","y":{"dtype":"f8","bdata":"w\u002fUoXAdmAUE="},"yaxis":"y","type":"bar","texttemplate":"%{y:$,.0f}"},{"hovertemplate":"City=%{x}\u003cbr\u003eAverage Salary (USD)=%{y}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"Nashville","marker":{"color":"rgb(252,141,98)","pattern":{"shape":""}},"name":"Nashville","orientation":"v","showlegend":true,"textposition":"outside","x":["Nashville"],"xaxis":"x","y":{"dtype":"f8","bdata":"16NwPc4ZAEE="},"yaxis":"y","type":"bar","texttemplate":"%{y:$,.0f}"},{"hovertemplate":"City=%{x}\u003cbr\u003eAverage Salary (USD)=%{y}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"Washington DC","marker":{"color":"rgb(141,160,203)","pattern":{"shape":""}},"name":"Washington DC","orientation":"v","showlegend":true,"textposition":"outside","x":["Washington DC"],"xaxis":"x","y":{"dtype":"f8","bdata":"mpmZmQHy\u002f0A="},"yaxis":"y","type":"bar","texttemplate":"%{y:$,.0f}"},{"hovertemplate":"City=%{x}\u003cbr\u003eAverage Salary (USD)=%{y}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"Seattle","marker":{"color":"rgb(231,138,195)","pattern":{"shape":""}},"name":"Seattle","orientation":"v","showlegend":true,"textposition":"outside","x":["Seattle"],"xaxis":"x","y":{"dtype":"f8","bdata":"UrgehZ\u002fb\u002f0A="},"yaxis":"y","type":"bar","texttemplate":"%{y:$,.0f}"},{"hovertemplate":"City=%{x}\u003cbr\u003eAverage Salary (USD)=%{y}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"Houston","marker":{"color":"rgb(166,216,84)","pattern":{"shape":""}},"name":"Houston","orientation":"v","showlegend":true,"textposition":"outside","x":["Houston"],"xaxis":"x","y":{"dtype":"f8","bdata":"hetRuHK8\u002fEA="},"yaxis":"y","type":"bar","texttemplate":"%{y:$,.0f}"},{"hovertemplate":"City=%{x}\u003cbr\u003eAverage Salary (USD)=%{y}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"Los Angeles","marker":{"color":"rgb(255,217,47)","pattern":{"shape":""}},"name":"Los Angeles","orientation":"v","showlegend":true,"textposition":"outside","x":["Los Angeles"],"xaxis":"x","y":{"dtype":"f8","bdata":"rkfhemgv\u002fEA="},"yaxis":"y","type":"bar","texttemplate":"%{y:$,.0f}"},{"hovertemplate":"City=%{x}\u003cbr\u003eAverage Salary (USD)=%{y}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"Boston","marker":{"color":"rgb(229,196,148)","pattern":{"shape":""}},"name":"Boston","orientation":"v","showlegend":true,"textposition":"outside","x":["Boston"],"xaxis":"x","y":{"dtype":"f8","bdata":"zczMzAy5+0A="},"yaxis":"y","type":"bar","texttemplate":"%{y:$,.0f}"},{"hovertemplate":"City=%{x}\u003cbr\u003eAverage Salary (USD)=%{y}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"New York","marker":{"color":"rgb(179,179,179)","pattern":{"shape":""}},"name":"New York","orientation":"v","showlegend":true,"textposition":"outside","x":["New York"],"xaxis":"x","y":{"dtype":"f8","bdata":"hetRuMqK+0A="},"yaxis":"y","type":"bar","texttemplate":"%{y:$,.0f}"},{"hovertemplate":"City=%{x}\u003cbr\u003eAverage Salary (USD)=%{y}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"Austin","marker":{"color":"rgb(102,194,165)","pattern":{"shape":""}},"name":"Austin","orientation":"v","showlegend":true,"textposition":"outside","x":["Austin"],"xaxis":"x","y":{"dtype":"f8","bdata":"MzMzM1P4+kA="},"yaxis":"y","type":"bar","texttemplate":"%{y:$,.0f}"},{"hovertemplate":"City=%{x}\u003cbr\u003eAverage Salary (USD)=%{y}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"Dallas","marker":{"color":"rgb(252,141,98)","pattern":{"shape":""}},"name":"Dallas","orientation":"v","showlegend":true,"textposition":"outside","x":["Dallas"],"xaxis":"x","y":{"dtype":"f8","bdata":"KVyPwulL+kA="},"yaxis":"y","type":"bar","texttemplate":"%{y:$,.0f}"},{"hovertemplate":"City=%{x}\u003cbr\u003eAverage Salary (USD)=%{y}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"Denver","marker":{"color":"rgb(141,160,203)","pattern":{"shape":""}},"name":"Denver","orientation":"v","showlegend":true,"textposition":"outside","x":["Denver"],"xaxis":"x","y":{"dtype":"f8","bdata":"cT0K189K+kA="},"yaxis":"y","type":"bar","texttemplate":"%{y:$,.0f}"},{"hovertemplate":"City=%{x}\u003cbr\u003eAverage Salary (USD)=%{y}\u003cextra\u003e\u003c\u002fextra\u003e","legendgroup":"Kansas City","marker":{"color":"rgb(231,138,195)","pattern":{"shape":""}},"name":"Kansas City","orientation":"v","showlegend":true,"textposition":"outside","x":["Kansas City"],"xaxis":"x","y":{"dtype":"f8","bdata":"SOF6FHr38kA="},"yaxis":"y","type":"bar","texttemplate":"%{y:$,.0f}"}],                        {"template":{"data":{"histogram2dcontour":[{"type":"histogram2dcontour","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"choropleth":[{"type":"choropleth","colorbar":{"outlinewidth":0,"ticks":""}}],"histogram2d":[{"type":"histogram2d","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"heatmap":[{"type":"heatmap","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"contourcarpet":[{"type":"contourcarpet","colorbar":{"outlinewidth":0,"ticks":""}}],"contour":[{"type":"contour","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"surface":[{"type":"surface","colorbar":{"outlinewidth":0,"ticks":""},"colorscale":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]]}],"mesh3d":[{"type":"mesh3d","colorbar":{"outlinewidth":0,"ticks":""}}],"scatter":[{"fillpattern":{"fillmode":"overlay","size":10,"solidity":0.2},"type":"scatter"}],"parcoords":[{"type":"parcoords","line":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterpolargl":[{"type":"scatterpolargl","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"bar":[{"error_x":{"color":"#2a3f5f"},"error_y":{"color":"#2a3f5f"},"marker":{"line":{"color":"#E5ECF6","width":0.5},"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"bar"}],"scattergeo":[{"type":"scattergeo","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterpolar":[{"type":"scatterpolar","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"histogram":[{"marker":{"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"histogram"}],"scattergl":[{"type":"scattergl","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatter3d":[{"type":"scatter3d","line":{"colorbar":{"outlinewidth":0,"ticks":""}},"marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattermap":[{"type":"scattermap","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattermapbox":[{"type":"scattermapbox","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scatterternary":[{"type":"scatterternary","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"scattercarpet":[{"type":"scattercarpet","marker":{"colorbar":{"outlinewidth":0,"ticks":""}}}],"carpet":[{"aaxis":{"endlinecolor":"#2a3f5f","gridcolor":"white","linecolor":"white","minorgridcolor":"white","startlinecolor":"#2a3f5f"},"baxis":{"endlinecolor":"#2a3f5f","gridcolor":"white","linecolor":"white","minorgridcolor":"white","startlinecolor":"#2a3f5f"},"type":"carpet"}],"table":[{"cells":{"fill":{"color":"#EBF0F8"},"line":{"color":"white"}},"header":{"fill":{"color":"#C8D4E3"},"line":{"color":"white"}},"type":"table"}],"barpolar":[{"marker":{"line":{"color":"#E5ECF6","width":0.5},"pattern":{"fillmode":"overlay","size":10,"solidity":0.2}},"type":"barpolar"}],"pie":[{"automargin":true,"type":"pie"}]},"layout":{"autotypenumbers":"strict","colorway":["#636efa","#EF553B","#00cc96","#ab63fa","#FFA15A","#19d3f3","#FF6692","#B6E880","#FF97FF","#FECB52"],"font":{"color":"#2a3f5f"},"hovermode":"closest","hoverlabel":{"align":"left"},"paper_bgcolor":"white","plot_bgcolor":"#E5ECF6","polar":{"bgcolor":"#E5ECF6","angularaxis":{"gridcolor":"white","linecolor":"white","ticks":""},"radialaxis":{"gridcolor":"white","linecolor":"white","ticks":""}},"ternary":{"bgcolor":"#E5ECF6","aaxis":{"gridcolor":"white","linecolor":"white","ticks":""},"baxis":{"gridcolor":"white","linecolor":"white","ticks":""},"caxis":{"gridcolor":"white","linecolor":"white","ticks":""}},"coloraxis":{"colorbar":{"outlinewidth":0,"ticks":""}},"colorscale":{"sequential":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]],"sequentialminus":[[0.0,"#0d0887"],[0.1111111111111111,"#46039f"],[0.2222222222222222,"#7201a8"],[0.3333333333333333,"#9c179e"],[0.4444444444444444,"#bd3786"],[0.5555555555555556,"#d8576b"],[0.6666666666666666,"#ed7953"],[0.7777777777777778,"#fb9f3a"],[0.8888888888888888,"#fdca26"],[1.0,"#f0f921"]],"diverging":[[0,"#8e0152"],[0.1,"#c51b7d"],[0.2,"#de77ae"],[0.3,"#f1b6da"],[0.4,"#fde0ef"],[0.5,"#f7f7f7"],[0.6,"#e6f5d0"],[0.7,"#b8e186"],[0.8,"#7fbc41"],[0.9,"#4d9221"],[1,"#276419"]]},"xaxis":{"gridcolor":"white","linecolor":"white","ticks":"","title":{"standoff":15},"zerolinecolor":"white","automargin":true,"zerolinewidth":2},"yaxis":{"gridcolor":"white","linecolor":"white","ticks":"","title":{"standoff":15},"zerolinecolor":"white","automargin":true,"zerolinewidth":2},"scene":{"xaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2},"yaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2},"zaxis":{"backgroundcolor":"#E5ECF6","gridcolor":"white","linecolor":"white","showbackground":true,"ticks":"","zerolinecolor":"white","gridwidth":2}},"shapedefaults":{"line":{"color":"#2a3f5f"}},"annotationdefaults":{"arrowcolor":"#2a3f5f","arrowhead":0,"arrowwidth":1},"geo":{"bgcolor":"white","landcolor":"#E5ECF6","subunitcolor":"white","showland":true,"showlakes":true,"lakecolor":"white"},"title":{"x":0.05},"mapbox":{"style":"light"},"margin":{"b":0,"l":0,"r":0,"t":30}}},"xaxis":{"anchor":"y","domain":[0.0,1.0],"title":{"text":"City"},"categoryorder":"array","categoryarray":["San Francisco","Nashville","Washington DC","Seattle","Houston","Los Angeles","Boston","New York","Austin","Dallas","Denver","Kansas City"],"tickangle":-45},"yaxis":{"anchor":"x","domain":[0.0,1.0],"title":{"text":"Average Salary (USD)"},"tickformat":"$,.0f"},"legend":{"title":{"text":"City"},"tracegroupgap":0},"title":{"text":"Average Salary Across Major US Cities"},"barmode":"relative","margin":{"l":50,"r":50,"t":80,"b":150},"showlegend":false,"height":500},                        {"responsive": true}                    ).then(function(){
                            
var gd = document.getElementById('92615ddf-a033-45e9-b08e-82e532ac9398');
var x = new MutationObserver(function (mutations, observer) {{
        var display = window.getComputedStyle(gd).display;
        if (!display || display === 'none') {{
            console.log([gd, 'removed!']);
            Plotly.purge(gd);
            observer.disconnect();
        }}
}});

// Listen for the removal of the full notebook cells
var notebookContainer = gd.closest('#notebook-container');
if (notebookContainer) {{
    x.observe(notebookContainer, {childList: true});
}}

// Listen for the clearing of the current output cell
var outputEl = gd.closest('.output');
if (outputEl) {{
    x.observe(outputEl, {childList: true});
}}

                        })                };            </script>        </div>
</div>
</div>
<p><strong>Insight:</strong> San Francisco leads with the highest average salary among major US metro areas, followed by Seattle and Boston. Southern cities like Nashville, Houston and Dallas show comparatively lower average salaries, reflecting regional cost-of-living differences and industry concentration patterns.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>